/**
 * This class is generated by jOOQ
 */
package org.labkey.gringotts.model.jooq;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.labkey.gringotts.model.jooq.tables.Records;
import org.labkey.gringotts.model.jooq.tables.Transactions;
import org.labkey.gringotts.model.jooq.tables.VaultColumns;
import org.labkey.gringotts.model.jooq.tables.VaultDatetimeValues;
import org.labkey.gringotts.model.jooq.tables.VaultIntValues;
import org.labkey.gringotts.model.jooq.tables.VaultLinks;
import org.labkey.gringotts.model.jooq.tables.VaultTextValues;
import org.labkey.gringotts.model.jooq.tables.Vaults;
import org.labkey.gringotts.model.jooq.tables.records.RecordsRecord;
import org.labkey.gringotts.model.jooq.tables.records.TransactionsRecord;
import org.labkey.gringotts.model.jooq.tables.records.VaultColumnsRecord;
import org.labkey.gringotts.model.jooq.tables.records.VaultDatetimeValuesRecord;
import org.labkey.gringotts.model.jooq.tables.records.VaultIntValuesRecord;
import org.labkey.gringotts.model.jooq.tables.records.VaultLinksRecord;
import org.labkey.gringotts.model.jooq.tables.records.VaultTextValuesRecord;
import org.labkey.gringotts.model.jooq.tables.records.VaultsRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>gringotts</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RecordsRecord> PK_RECORDS = UniqueKeys0.PK_RECORDS;
    public static final UniqueKey<TransactionsRecord> PK_TRANSACTIONS = UniqueKeys0.PK_TRANSACTIONS;
    public static final UniqueKey<TransactionsRecord> TRANSACTIONS_ID_UNIQUE = UniqueKeys0.TRANSACTIONS_ID_UNIQUE;
    public static final UniqueKey<VaultColumnsRecord> PK_VAULT_COLUMNS = UniqueKeys0.PK_VAULT_COLUMNS;
    public static final UniqueKey<VaultDatetimeValuesRecord> PK_VAULT_DATETIME_VALUES = UniqueKeys0.PK_VAULT_DATETIME_VALUES;
    public static final UniqueKey<VaultIntValuesRecord> PK_VAULT_INT_VALUES = UniqueKeys0.PK_VAULT_INT_VALUES;
    public static final UniqueKey<VaultLinksRecord> PK_VAULT_LINKS = UniqueKeys0.PK_VAULT_LINKS;
    public static final UniqueKey<VaultTextValuesRecord> PK_VAULT_TEXT_VALUES = UniqueKeys0.PK_VAULT_TEXT_VALUES;
    public static final UniqueKey<VaultsRecord> PK_VAULTS = UniqueKeys0.PK_VAULTS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<VaultDatetimeValuesRecord, TransactionsRecord> VAULT_DATETIME_VALUES__FK_VAULT_DATETIME_VALUES_TRANSACTIONS = ForeignKeys0.VAULT_DATETIME_VALUES__FK_VAULT_DATETIME_VALUES_TRANSACTIONS;
    public static final ForeignKey<VaultIntValuesRecord, TransactionsRecord> VAULT_INT_VALUES__FK_VAULT_INT_VALUES_TRANSACTIONS = ForeignKeys0.VAULT_INT_VALUES__FK_VAULT_INT_VALUES_TRANSACTIONS;
    public static final ForeignKey<VaultTextValuesRecord, TransactionsRecord> VAULT_TEXT_VALUES__FK_VAULT_TEXT_VALUES_TRANSACTIONS = ForeignKeys0.VAULT_TEXT_VALUES__FK_VAULT_TEXT_VALUES_TRANSACTIONS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RecordsRecord> PK_RECORDS = createUniqueKey(Records.RECORDS, "pk_records", Records.RECORDS.VAULTID, Records.RECORDS.RECORDID, Records.RECORDS.VERSION);
        public static final UniqueKey<TransactionsRecord> PK_TRANSACTIONS = createUniqueKey(Transactions.TRANSACTIONS, "pk_transactions", Transactions.TRANSACTIONS.CREATEDON);
        public static final UniqueKey<TransactionsRecord> TRANSACTIONS_ID_UNIQUE = createUniqueKey(Transactions.TRANSACTIONS, "transactions_id_unique", Transactions.TRANSACTIONS.TRANSACTIONID);
        public static final UniqueKey<VaultColumnsRecord> PK_VAULT_COLUMNS = createUniqueKey(VaultColumns.VAULT_COLUMNS, "pk_vault_columns", VaultColumns.VAULT_COLUMNS.VAULTID, VaultColumns.VAULT_COLUMNS.VERSION, VaultColumns.VAULT_COLUMNS.COLUMNNAME);
        public static final UniqueKey<VaultDatetimeValuesRecord> PK_VAULT_DATETIME_VALUES = createUniqueKey(VaultDatetimeValues.VAULT_DATETIME_VALUES, "pk_vault_datetime_values", VaultDatetimeValues.VAULT_DATETIME_VALUES.VAULTID, VaultDatetimeValues.VAULT_DATETIME_VALUES.RECORDID, VaultDatetimeValues.VAULT_DATETIME_VALUES.COLUMNID, VaultDatetimeValues.VAULT_DATETIME_VALUES.TRANSACTIONID);
        public static final UniqueKey<VaultIntValuesRecord> PK_VAULT_INT_VALUES = createUniqueKey(VaultIntValues.VAULT_INT_VALUES, "pk_vault_int_values", VaultIntValues.VAULT_INT_VALUES.VAULTID, VaultIntValues.VAULT_INT_VALUES.RECORDID, VaultIntValues.VAULT_INT_VALUES.COLUMNID, VaultIntValues.VAULT_INT_VALUES.TRANSACTIONID);
        public static final UniqueKey<VaultLinksRecord> PK_VAULT_LINKS = createUniqueKey(VaultLinks.VAULT_LINKS, "pk_vault_links", VaultLinks.VAULT_LINKS.VAULTID1, VaultLinks.VAULT_LINKS.COLUMNID, VaultLinks.VAULT_LINKS.VAULTID2, VaultLinks.VAULT_LINKS.RECORD1, VaultLinks.VAULT_LINKS.RECORD2, VaultLinks.VAULT_LINKS.TRANSACTIONID);
        public static final UniqueKey<VaultTextValuesRecord> PK_VAULT_TEXT_VALUES = createUniqueKey(VaultTextValues.VAULT_TEXT_VALUES, "pk_vault_text_values", VaultTextValues.VAULT_TEXT_VALUES.VAULTID, VaultTextValues.VAULT_TEXT_VALUES.RECORDID, VaultTextValues.VAULT_TEXT_VALUES.COLUMNID, VaultTextValues.VAULT_TEXT_VALUES.TRANSACTIONID);
        public static final UniqueKey<VaultsRecord> PK_VAULTS = createUniqueKey(Vaults.VAULTS, "pk_vaults", Vaults.VAULTS.VAULTID, Vaults.VAULTS.CREATED);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<VaultDatetimeValuesRecord, TransactionsRecord> VAULT_DATETIME_VALUES__FK_VAULT_DATETIME_VALUES_TRANSACTIONS = createForeignKey(org.labkey.gringotts.model.jooq.Keys.TRANSACTIONS_ID_UNIQUE, VaultDatetimeValues.VAULT_DATETIME_VALUES, "vault_datetime_values__fk_vault_datetime_values_transactions", VaultDatetimeValues.VAULT_DATETIME_VALUES.TRANSACTIONID);
        public static final ForeignKey<VaultIntValuesRecord, TransactionsRecord> VAULT_INT_VALUES__FK_VAULT_INT_VALUES_TRANSACTIONS = createForeignKey(org.labkey.gringotts.model.jooq.Keys.TRANSACTIONS_ID_UNIQUE, VaultIntValues.VAULT_INT_VALUES, "vault_int_values__fk_vault_int_values_transactions", VaultIntValues.VAULT_INT_VALUES.TRANSACTIONID);
        public static final ForeignKey<VaultTextValuesRecord, TransactionsRecord> VAULT_TEXT_VALUES__FK_VAULT_TEXT_VALUES_TRANSACTIONS = createForeignKey(org.labkey.gringotts.model.jooq.Keys.TRANSACTIONS_ID_UNIQUE, VaultTextValues.VAULT_TEXT_VALUES, "vault_text_values__fk_vault_text_values_transactions", VaultTextValues.VAULT_TEXT_VALUES.TRANSACTIONID);
    }
}
