networks:
  networkExt:
    name: sharedservices
    external: true

services:
  labkeydev:
    image: wnprcehr/labkeysnapshot:21.11
    volumes:
      - "${LK_FILES_DIR}:/backups/new_files_dir"
      - "${LK_LOG_DIR}:/usr/local/tomcat/logs"
      - "${LK_MODULE_DEPLOY_DIR}:/usr/local/modules"
      - "${LK_SESSION_DIR}:/usr/local/labkey/sessions"
    expose:
      - "8080"
    networks:
      - networkExt
    environment:
      CATALINA_OPTS:
      JAVA_OPTS: "${LK_JAVA_OPTS} -Djdbc.user=${PG_USER} -Djdbc.pass=${PG_PASS} -Djdbc.url=jdbc:postgresql://postgres:5432/${PG_NAME} \
                  -Dmsql.user=${LK_MSQL_USER} -Dmsql.pass=${LK_MSQL_PASS} -Dmsql.url=\"${LK_MSQL_URL}\" \
                  -Dlabkey.masterEncryptionKey=${LK_MASTER_ENCRYPTION_KEY} \
                  -Dlog4j2.formatMsgNoLookups=true"
      LK_BACKGROUND_USER: ${LK_BACKGROUND_USER}
      LK_BACKGROUND_USER_PASSWORD: ${LK_BACKGROUND_USER_PASSWORD}
      LK_BASE_URL: ${LK_BASE_URL}
      PG_NAME:
      PG_PASS:
      PG_USER:
      LK_MSQL_USER:
      LK_MSQL_PASS:
      LK_MSQL_URL:
      TZ: America/Chicago

  nginx:
    image: nginx:1.18.0
    volumes:
      - "${NGINX_CLIENT_CER_FILE}:/usr/local/ssl/client-ca.pem"
      - "${NGINX_CLIENT_CRL_FILE}:/usr/local/ssl/crl.pem"
      - "${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf"
      - "${NGINX_SERVER_CER_FILE}:/usr/local/ssl/cert.pem"
      - "${NGINX_SERVER_PASS_FILE}:/usr/local/ssl/key.pass"
      - "${NGINX_SERVER_KEY_FILE}:/usr/local/ssl/key.pem"
      - "${NGINX_WELL_KNOWN_DIR}:/usr/share/nginx/html"
    ports:
      - "${LK_DANGER_PORT}:80"
      - "${LK_SECURE_PORT}:443"
    networks:
      - networkExt
    environment:
      TZ: America/Chicago
