version: "3.5"
networks:
  networkExt:
    external:
      name: sharedservices

services:
  labkeydev:
    image: wnprcehr/labkeydev:18.3
    volumes:
      - "${LABKEY_FILES_DIR}:/backups/new_files_dir"
      - "${LABKEY_LOG_DIR}:/usr/local/tomcat/logs"
      - "${LABKEY_MODULE_DEPLOY_DIR}:/usr/local/modules"
      - "${LABKEY_SESSION_DIR}:/usr/local/labkey/sessions"
    expose:
      - "8080"
    networks:
      - networkExt
    environment:
      CATALINA_OPTS:
      JAVA_OPTS: "${JAVA_OPTS} -Djdbc.user=${PG_USER} -Djdbc.pass=${PG_PASS} -Djdbc.url=jdbc:postgresql://postgres:5432/${PG_NAME} \
                  -Dmsql.user=${MSQL_USER} -Dmsql.pass=${MSQL_PASS} -Dmsql.url=${MSQL_URL} \
                  -Dlabkey.masterEncryptionKey=${LABKEY_MASTER_ENCRYPTION_KEY}"
      PG_NAME:
      PG_PASS:
      PG_USER:
      MSQL_USER:
      MSQL_PASS:
      MSQL_URL:
      TZ: America/Chicago

  nginx:
    image: nginx:1.13.0
    volumes:
      - "${NGINX_CLIENT_CER_FILE}:/usr/local/ssl/client-ca.pem"
      - "${NGINX_CLIENT_CRL_FILE}:/usr/local/ssl/crl.pem"
      - "${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf"
      - "${NGINX_SERVER_CER_FILE}:/usr/local/ssl/cert.pem"
      - "${NGINX_SERVER_PASS_FILE}:/usr/local/ssl/key.pass"
      - "${NGINX_SERVER_KEY_FILE}:/usr/local/ssl/key.pem"
      - "${NGINX_WELL_KNOWN_DIR}:/usr/share/nginx/html"
    ports:
      - "${LABKEY_DANGER_PORT}:80"
      - "${LABKEY_SECURE_PORT}:443"
    networks:
      - networkExt
    environment:
      TZ: America/Chicago
