/**
 * This class is generated by jOOQ
 */
package org.labkey.deviceproxy.model.jooq.tables.records;


import java.sql.Timestamp;

import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.deviceproxy.model.jooq.tables.AllowedService;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedServiceRecord extends UpdatableRecordImpl<AllowedServiceRecord> implements Record4<String, Timestamp, String, String> {

    private static final long serialVersionUID = 364142601;

    /**
     * Setter for <code>deviceproxy.allowed_service.public_key</code>.
     */
    public void setPublicKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>deviceproxy.allowed_service.public_key</code>.
     */
    public String getPublicKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>deviceproxy.allowed_service.start_time</code>.
     */
    public void setStartTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>deviceproxy.allowed_service.start_time</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>deviceproxy.allowed_service.module_name</code>.
     */
    public void setModuleName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>deviceproxy.allowed_service.module_name</code>.
     */
    public String getModuleName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>deviceproxy.allowed_service.service_name</code>.
     */
    public void setServiceName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>deviceproxy.allowed_service.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record4<String, Timestamp, String, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Timestamp, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Timestamp, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AllowedService.ALLOWED_SERVICE.PUBLIC_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return AllowedService.ALLOWED_SERVICE.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AllowedService.ALLOWED_SERVICE.MODULE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AllowedService.ALLOWED_SERVICE.SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPublicKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getModuleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServiceRecord value1(String value) {
        setPublicKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServiceRecord value2(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServiceRecord value3(String value) {
        setModuleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServiceRecord value4(String value) {
        setServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServiceRecord values(String value1, Timestamp value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedServiceRecord
     */
    public AllowedServiceRecord() {
        super(AllowedService.ALLOWED_SERVICE);
    }

    /**
     * Create a detached, initialised AllowedServiceRecord
     */
    public AllowedServiceRecord(String publicKey, Timestamp startTime, String moduleName, String serviceName) {
        super(AllowedService.ALLOWED_SERVICE);

        set(0, publicKey);
        set(1, startTime);
        set(2, moduleName);
        set(3, serviceName);
    }
}
