/**
 * This class is generated by jOOQ
 */
package org.labkey.deviceproxy.model.jooq.tables.records;


import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.deviceproxy.model.jooq.tables.Device;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceRecord extends UpdatableRecordImpl<DeviceRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -2005448569;

    /**
     * Setter for <code>deviceproxy.device.public_key</code>.
     */
    public void setPublicKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>deviceproxy.device.public_key</code>.
     */
    public String getPublicKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>deviceproxy.device.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>deviceproxy.device.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>deviceproxy.device.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>deviceproxy.device.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Device.DEVICE.PUBLIC_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Device.DEVICE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Device.DEVICE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPublicKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value1(String value) {
        setPublicKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceRecord
     */
    public DeviceRecord() {
        super(Device.DEVICE);
    }

    /**
     * Create a detached, initialised DeviceRecord
     */
    public DeviceRecord(String publicKey, String name, String description) {
        super(Device.DEVICE);

        set(0, publicKey);
        set(1, name);
        set(2, description);
    }
}
