select calendar_id,calendar_type,display_name,api_action,folder_id,show_by_default,default_bg_color
from wnprc.surgery_procedure_calendars
union all
select email,'Office365Resource',displayname,'FetchSurgeryProcedureOutlookEvents','rooms',show_by_default,default_bg_color
from wnprc.surgery_procedure_rooms