/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.AllowedSurgeries;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedSurgeriesRecord extends UpdatableRecordImpl<AllowedSurgeriesRecord> implements Record11<String, String, String, String, Integer, Integer, Integer, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -1753487434;

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.surgery_id</code>.
     */
    public void setSurgeryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.surgery_id</code>.
     */
    public String getSurgeryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.survival_type</code>.
     */
    public void setSurvivalType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.survival_type</code>.
     */
    public String getSurvivalType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.estimated_duration_in_minutes</code>.
     */
    public void setEstimatedDurationInMinutes(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.estimated_duration_in_minutes</code>.
     */
    public Integer getEstimatedDurationInMinutes() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.min_fast_hours</code>.
     */
    public void setMinFastHours(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.min_fast_hours</code>.
     */
    public Integer getMinFastHours() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.max_fast_hours</code>.
     */
    public void setMaxFastHours(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.max_fast_hours</code>.
     */
    public Integer getMaxFastHours() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_surgeries.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_surgeries.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, Integer, Integer, Integer, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, Integer, Integer, Integer, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AllowedSurgeries.ALLOWED_SURGERIES.SURGERY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AllowedSurgeries.ALLOWED_SURGERIES.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AllowedSurgeries.ALLOWED_SURGERIES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AllowedSurgeries.ALLOWED_SURGERIES.SURVIVAL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return AllowedSurgeries.ALLOWED_SURGERIES.ESTIMATED_DURATION_IN_MINUTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return AllowedSurgeries.ALLOWED_SURGERIES.MIN_FAST_HOURS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return AllowedSurgeries.ALLOWED_SURGERIES.MAX_FAST_HOURS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return AllowedSurgeries.ALLOWED_SURGERIES.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return AllowedSurgeries.ALLOWED_SURGERIES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return AllowedSurgeries.ALLOWED_SURGERIES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return AllowedSurgeries.ALLOWED_SURGERIES.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSurgeryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSurvivalType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getEstimatedDurationInMinutes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMinFastHours();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getMaxFastHours();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value1(String value) {
        setSurgeryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value4(String value) {
        setSurvivalType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value5(Integer value) {
        setEstimatedDurationInMinutes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value6(Integer value) {
        setMinFastHours(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value7(Integer value) {
        setMaxFastHours(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value8(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value9(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value10(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord value11(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesRecord values(String value1, String value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Timestamp value9, Integer value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedSurgeriesRecord
     */
    public AllowedSurgeriesRecord() {
        super(AllowedSurgeries.ALLOWED_SURGERIES);
    }

    /**
     * Create a detached, initialised AllowedSurgeriesRecord
     */
    public AllowedSurgeriesRecord(String surgeryId, String title, String description, String survivalType, Integer estimatedDurationInMinutes, Integer minFastHours, Integer maxFastHours, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(AllowedSurgeries.ALLOWED_SURGERIES);

        set(0, surgeryId);
        set(1, title);
        set(2, description);
        set(3, survivalType);
        set(4, estimatedDurationInMinutes);
        set(5, minFastHours);
        set(6, maxFastHours);
        set(7, createdby);
        set(8, created);
        set(9, modifiedby);
        set(10, modified);
    }
}
