/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.AllowedSpeciesToDrugs;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedSpeciesToDrugsRecord extends UpdatableRecordImpl<AllowedSpeciesToDrugsRecord> implements Record7<String, String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 1296833167;

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.protocol_revision_id</code>.
     */
    public void setProtocolRevisionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.protocol_revision_id</code>.
     */
    public String getProtocolRevisionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.species_class</code>.
     */
    public void setSpeciesClass(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.species_class</code>.
     */
    public String getSpeciesClass() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.drug_id</code>.
     */
    public void setDrugId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.drug_id</code>.
     */
    public String getDrugId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.allowed_species_to_drugs.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.allowed_species_to_drugs.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.PROTOCOL_REVISION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.SPECIES_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.DRUG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProtocolRevisionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpeciesClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDrugId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value1(String value) {
        setProtocolRevisionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value2(String value) {
        setSpeciesClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value3(String value) {
        setDrugId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value4(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value6(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord value7(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToDrugsRecord values(String value1, String value2, String value3, Integer value4, Timestamp value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedSpeciesToDrugsRecord
     */
    public AllowedSpeciesToDrugsRecord() {
        super(AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS);
    }

    /**
     * Create a detached, initialised AllowedSpeciesToDrugsRecord
     */
    public AllowedSpeciesToDrugsRecord(String protocolRevisionId, String speciesClass, String drugId, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(AllowedSpeciesToDrugs.ALLOWED_SPECIES_TO_DRUGS);

        set(0, protocolRevisionId);
        set(1, speciesClass);
        set(2, drugId);
        set(3, createdby);
        set(4, created);
        set(5, modifiedby);
        set(6, modified);
    }
}
