/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.MeaslesClearances;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeaslesClearancesRecord extends UpdatableRecordImpl<MeaslesClearancesRecord> implements Record8<String, Timestamp, String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -258883845;

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.date</code>.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.comment</code>.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.comment</code>.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.container</code>.
     */
    public void setContainer(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.container</code>.
     */
    public String getContainer() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>wnprc_compliance.measles_clearances.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>wnprc_compliance.measles_clearances.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Timestamp, String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Timestamp, String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MeaslesClearances.MEASLES_CLEARANCES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return MeaslesClearances.MEASLES_CLEARANCES.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MeaslesClearances.MEASLES_CLEARANCES.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MeaslesClearances.MEASLES_CLEARANCES.CONTAINER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MeaslesClearances.MEASLES_CLEARANCES.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MeaslesClearances.MEASLES_CLEARANCES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return MeaslesClearances.MEASLES_CLEARANCES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MeaslesClearances.MEASLES_CLEARANCES.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value3(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value4(String value) {
        setContainer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value5(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value6(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value7(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord value8(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeaslesClearancesRecord values(String value1, Timestamp value2, String value3, String value4, Integer value5, Timestamp value6, Integer value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeaslesClearancesRecord
     */
    public MeaslesClearancesRecord() {
        super(MeaslesClearances.MEASLES_CLEARANCES);
    }

    /**
     * Create a detached, initialised MeaslesClearancesRecord
     */
    public MeaslesClearancesRecord(String id, Timestamp date, String comment, String container, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(MeaslesClearances.MEASLES_CLEARANCES);

        set(0, id);
        set(1, date);
        set(2, comment);
        set(3, container);
        set(4, createdby);
        set(5, created);
        set(6, modifiedby);
        set(7, modified);
    }
}
