/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.PersonsPendingTbClearances;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsPendingTbClearancesRecord extends UpdatableRecordImpl<PersonsPendingTbClearancesRecord> implements Record7<String, String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -467464094;

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.person_id</code>.
     */
    public void setPersonId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.person_id</code>.
     */
    public String getPersonId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.clearance_id</code>.
     */
    public void setClearanceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.clearance_id</code>.
     */
    public String getClearanceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.container</code>.
     */
    public void setContainer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.container</code>.
     */
    public String getContainer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.persons_pending_tb_clearances.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.persons_pending_tb_clearances.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.CLEARANCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.CONTAINER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClearanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value1(String value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value2(String value) {
        setClearanceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value3(String value) {
        setContainer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value4(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value6(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord value7(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsPendingTbClearancesRecord values(String value1, String value2, String value3, Integer value4, Timestamp value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonsPendingTbClearancesRecord
     */
    public PersonsPendingTbClearancesRecord() {
        super(PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES);
    }

    /**
     * Create a detached, initialised PersonsPendingTbClearancesRecord
     */
    public PersonsPendingTbClearancesRecord(String personId, String clearanceId, String container, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(PersonsPendingTbClearances.PERSONS_PENDING_TB_CLEARANCES);

        set(0, personId);
        set(1, clearanceId);
        set(2, container);
        set(3, createdby);
        set(4, created);
        set(5, modifiedby);
        set(6, modified);
    }
}
