/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.ProtocolRevisions;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtocolRevisionsRecord extends UpdatableRecordImpl<ProtocolRevisionsRecord> implements Record22<String, String, String, String, String, Timestamp, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, String, Boolean, Boolean, Boolean, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 407285314;

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.protocol_id</code>.
     */
    public void setProtocolId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.protocol_id</code>.
     */
    public String getProtocolId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.principal_investigator_id</code>.
     */
    public void setPrincipalInvestigatorId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.principal_investigator_id</code>.
     */
    public String getPrincipalInvestigatorId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.spi_primary_id</code>.
     */
    public void setSpiPrimaryId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.spi_primary_id</code>.
     */
    public String getSpiPrimaryId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.spi_secondary_id</code>.
     */
    public void setSpiSecondaryId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.spi_secondary_id</code>.
     */
    public String getSpiSecondaryId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.approval_date</code>.
     */
    public void setApprovalDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.approval_date</code>.
     */
    public Timestamp getApprovalDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.attached_file_id</code>.
     */
    public void setAttachedFileId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.attached_file_id</code>.
     */
    public String getAttachedFileId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.usda_designation</code>.
     */
    public void setUsdaDesignation(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.usda_designation</code>.
     */
    public String getUsdaDesignation() {
        return (String) get(7);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_biological_hazards</code>.
     */
    public void setHasBiologicalHazards(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_biological_hazards</code>.
     */
    public Boolean getHasBiologicalHazards() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_chemical_hazards</code>.
     */
    public void setHasChemicalHazards(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_chemical_hazards</code>.
     */
    public Boolean getHasChemicalHazards() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_physical_hazards</code>.
     */
    public void setHasPhysicalHazards(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_physical_hazards</code>.
     */
    public Boolean getHasPhysicalHazards() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_radiation_hazards</code>.
     */
    public void setHasRadiationHazards(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_radiation_hazards</code>.
     */
    public Boolean getHasRadiationHazards() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_wildlife_hazards</code>.
     */
    public void setHasWildlifeHazards(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_wildlife_hazards</code>.
     */
    public Boolean getHasWildlifeHazards() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_other_hazards</code>.
     */
    public void setHasOtherHazards(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_other_hazards</code>.
     */
    public Boolean getHasOtherHazards() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.other_hazards_notes</code>.
     */
    public void setOtherHazardsNotes(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.other_hazards_notes</code>.
     */
    public String getOtherHazardsNotes() {
        return (String) get(14);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.has_recombinant_material_hazards</code>.
     */
    public void setHasRecombinantMaterialHazards(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.has_recombinant_material_hazards</code>.
     */
    public Boolean getHasRecombinantMaterialHazards() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.involves_euthanasia</code>.
     */
    public void setInvolvesEuthanasia(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.involves_euthanasia</code>.
     */
    public Boolean getInvolvesEuthanasia() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.allows_single_housing</code>.
     */
    public void setAllowsSingleHousing(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.allows_single_housing</code>.
     */
    public Boolean getAllowsSingleHousing() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>wnprc_compliance.protocol_revisions.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocol_revisions.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<String, String, String, String, String, Timestamp, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, String, Boolean, Boolean, Boolean, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<String, String, String, String, String, Timestamp, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, String, Boolean, Boolean, Boolean, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.PROTOCOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.PRINCIPAL_INVESTIGATOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.SPI_PRIMARY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.SPI_SECONDARY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.APPROVAL_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.ATTACHED_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.USDA_DESIGNATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_BIOLOGICAL_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_CHEMICAL_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_PHYSICAL_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_RADIATION_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_WILDLIFE_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_OTHER_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.OTHER_HAZARDS_NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.HAS_RECOMBINANT_MATERIAL_HAZARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.INVOLVES_EUTHANASIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field18() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.ALLOWS_SINGLE_HOUSING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field20() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field21() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field22() {
        return ProtocolRevisions.PROTOCOL_REVISIONS.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProtocolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrincipalInvestigatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSpiPrimaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSpiSecondaryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getApprovalDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAttachedFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUsdaDesignation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getHasBiologicalHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getHasChemicalHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getHasPhysicalHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getHasRadiationHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getHasWildlifeHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getHasOtherHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getOtherHazardsNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getHasRecombinantMaterialHazards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getInvolvesEuthanasia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value18() {
        return getAllowsSingleHousing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value20() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value21() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value22() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value2(String value) {
        setProtocolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value3(String value) {
        setPrincipalInvestigatorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value4(String value) {
        setSpiPrimaryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value5(String value) {
        setSpiSecondaryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value6(Timestamp value) {
        setApprovalDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value7(String value) {
        setAttachedFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value8(String value) {
        setUsdaDesignation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value9(Boolean value) {
        setHasBiologicalHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value10(Boolean value) {
        setHasChemicalHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value11(Boolean value) {
        setHasPhysicalHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value12(Boolean value) {
        setHasRadiationHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value13(Boolean value) {
        setHasWildlifeHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value14(Boolean value) {
        setHasOtherHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value15(String value) {
        setOtherHazardsNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value16(Boolean value) {
        setHasRecombinantMaterialHazards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value17(Boolean value) {
        setInvolvesEuthanasia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value18(Boolean value) {
        setAllowsSingleHousing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value19(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value20(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value21(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord value22(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisionsRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, String value8, Boolean value9, Boolean value10, Boolean value11, Boolean value12, Boolean value13, Boolean value14, String value15, Boolean value16, Boolean value17, Boolean value18, Integer value19, Timestamp value20, Integer value21, Timestamp value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtocolRevisionsRecord
     */
    public ProtocolRevisionsRecord() {
        super(ProtocolRevisions.PROTOCOL_REVISIONS);
    }

    /**
     * Create a detached, initialised ProtocolRevisionsRecord
     */
    public ProtocolRevisionsRecord(String id, String protocolId, String principalInvestigatorId, String spiPrimaryId, String spiSecondaryId, Timestamp approvalDate, String attachedFileId, String usdaDesignation, Boolean hasBiologicalHazards, Boolean hasChemicalHazards, Boolean hasPhysicalHazards, Boolean hasRadiationHazards, Boolean hasWildlifeHazards, Boolean hasOtherHazards, String otherHazardsNotes, Boolean hasRecombinantMaterialHazards, Boolean involvesEuthanasia, Boolean allowsSingleHousing, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(ProtocolRevisions.PROTOCOL_REVISIONS);

        set(0, id);
        set(1, protocolId);
        set(2, principalInvestigatorId);
        set(3, spiPrimaryId);
        set(4, spiSecondaryId);
        set(5, approvalDate);
        set(6, attachedFileId);
        set(7, usdaDesignation);
        set(8, hasBiologicalHazards);
        set(9, hasChemicalHazards);
        set(10, hasPhysicalHazards);
        set(11, hasRadiationHazards);
        set(12, hasWildlifeHazards);
        set(13, hasOtherHazards);
        set(14, otherHazardsNotes);
        set(15, hasRecombinantMaterialHazards);
        set(16, involvesEuthanasia);
        set(17, allowsSingleHousing);
        set(18, createdby);
        set(19, created);
        set(20, modifiedby);
        set(21, modified);
    }
}
