SELECT "Blood Draws".Id,
       "Blood Draws".date,
       "Blood Draws".tube_type,
       "Blood Draws".tube_vol,
       "Blood Draws".quantity,
       "Blood Draws".performedby,
       "Blood Draws".requestor,
       "Blood Draws".project,
       "Blood Draws".assayCode,
       "Blood Draws".billedby,
       "Blood Draws".num_tubes,
       "Blood Draws".remark,
       "Blood Draws".additionalServices,
       "Blood Draws".account,
       "Blood Draws".daterequested,
       "Blood Draws".restraint,
       "Blood Draws".restraintTime,
       "Blood Draws".instructions,
       "Blood Draws".restraintDuration,
       "Blood Draws".BloodRemaining.AvailBlood,
       "Blood Draws".QCState,
       "Blood Draws".QCState.label
FROM "Blood Draws"
WHERE "Blood Draws".BloodRemaining.AvailBlood < CAST(moduleProperty('WNPRC_EHR', 'BloodDrawThreshold') as INTEGER) AND  "Blood Draws".date > curdate() AND "Blood Draws".date < cast(TIMESTAMPADD('SQL_TSI_DAY', 1, curdate()) as date) AND "Blood Draws".QCState.label <> 'Request: Denied'