SELECT b.Id,
       b.date,
       b.tube_type,
       b.tube_vol,
       b.quantity,
       b.performedby,
       b.requestor,
       b.project,
       b.assayCode,
       b.billedby,
       b.num_tubes,
       b.remark,
       b.additionalServices,
       b.account,
       b.daterequested,
       b.restraint,
       b.restraintTime,
       b.instructions,
       b.restraintDuration,
       b.BloodRemaining.allowableBlood,
       b.QCState,
       b.QCState.label
FROM "Blood Draws" b
LEFT JOIN ehr_lookups.species e ON e.common = b.Id.Demographics.species
WHERE b.BloodRemaining.allowableBlood < e.blood_threshold_warning AND  b.date > curdate() AND b.date < cast(TIMESTAMPADD('SQL_TSI_DAY', 1, curdate()) as date) AND b.QCState.label <> 'Request: Denied'