-- this query will be used to get the columns for the template
SELECT
  ru.Id,
  ru.date,
  ru.pregnancyid,
  ru.project,
  ru.account,
  ru.fetal_heartbeat,
  ru.beats_per_minute,
  ru.crown_rump_mm,
  ru.biparietal_diameter_mm,
  ru.head_circumference_mm,
  ru.occipital_frontal_diameter_mm,
  ru.abdominal_circumference_mm,
  ru.femur_length_mm,
  ru.ua_peak_systolic_velocity_cms,
  ru.ua_end_diastolic_velocity_cms,
  ru.ua_systolic_diastolic_ratio,
  ru.lateral_ventricles_mm,
  ru.cerebellum_mm,
  ru.cisterna_magna_mm,
  ru.max_vertical_pocket_cm,
  ru.amniotic_fluid_index_cm,
  ru.mca_peak_systolic_cms,
  ru.mca_end_diastolic_cms,
  ru.mca_systolic_diastolic_ratio,
  ru.mca_pulsatility_index,
  ru.mca_resistive_index,
  ru.cardiac_circumference_mm,
  ru.cardiac_area_cm2,
  ru.chest_circumference_cm,
  ru.chest_area_cm2,
  ru.ratio_circumferences,
  ru.ratio_areas,
  ru.estimated_fetal_weight_g,
  ru.gest_sac_mm,
  ru.peak_systolic_cms,
  ru.end_diastolic_cms,
  ru.nuchal_fold,
  ru.code,
  ru.performedby,
  ru.findings AS ultrasoundFindings,
  ru.remark AS ultrasoundRemarks,
  r.restraintType,
  r.remarks AS restraintRemarks,
  ur.date AS reviewDate,
  ur.head,
  ur.falx,
  ur.thalamus,
  ur.lateral_ventricles,
  ur.choroid_plexus,
  ur.eye,
  ur.profile,
  ur.four_chamber_heart,
  ur.diaphragm,
  ur.stomach,
  ur.bowel,
  ur.bladder,
  ur.findings AS reviewFindings,
  ur.placenta_notes,
  ur.remarks AS reviewRemarks,
  ur.completed
  FROM study.research_ultrasounds ru
  JOIN study.ultrasound_review ur
    ON ru.objectid = ur.ultrasound_id
  JOIN study.restraints r
    ON ru.taskid = r.taskid