PARAMETERS(STARTTARGET TIMESTAMP , ENDTARGETDATE TIMESTAMP)
SELECT
    *,
    ENDTARGETDATE AS reportEndDate,

FROM ehr_lookups.calendar
WHERE (TargetDate >= STARTTARGET AND TargetDate <= ENDTARGETDATE)