/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.AllowedSpeciesToAllowedProceduresRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedSpeciesToAllowedProcedures extends TableImpl<AllowedSpeciesToAllowedProceduresRecord> {

    private static final long serialVersionUID = 1428131717;

    /**
     * The reference instance of <code>wnprc_compliance.allowed_species_to_allowed_procedures</code>
     */
    public static final AllowedSpeciesToAllowedProcedures ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES = new AllowedSpeciesToAllowedProcedures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AllowedSpeciesToAllowedProceduresRecord> getRecordType() {
        return AllowedSpeciesToAllowedProceduresRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.protocol_revision_id</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, String> PROTOCOL_REVISION_ID = createField("protocol_revision_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.species_classifier</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, String> SPECIES_CLASSIFIER = createField("species_classifier", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.allowed_procedure_id</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, String> ALLOWED_PROCEDURE_ID = createField("allowed_procedure_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.createdby</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.created</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.modifiedby</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.allowed_species_to_allowed_procedures.modified</code>.
     */
    public final TableField<AllowedSpeciesToAllowedProceduresRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.allowed_species_to_allowed_procedures</code> table reference
     */
    public AllowedSpeciesToAllowedProcedures() {
        this("allowed_species_to_allowed_procedures", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.allowed_species_to_allowed_procedures</code> table reference
     */
    public AllowedSpeciesToAllowedProcedures(String alias) {
        this(alias, ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES);
    }

    private AllowedSpeciesToAllowedProcedures(String alias, Table<AllowedSpeciesToAllowedProceduresRecord> aliased) {
        this(alias, aliased, null);
    }

    private AllowedSpeciesToAllowedProcedures(String alias, Table<AllowedSpeciesToAllowedProceduresRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AllowedSpeciesToAllowedProceduresRecord> getPrimaryKey() {
        return Keys.PK_ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AllowedSpeciesToAllowedProceduresRecord>> getKeys() {
        return Arrays.<UniqueKey<AllowedSpeciesToAllowedProceduresRecord>>asList(Keys.PK_ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AllowedSpeciesToAllowedProceduresRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AllowedSpeciesToAllowedProceduresRecord, ?>>asList(Keys.ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES__FK_ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES_ALLOWED_SPECIES, Keys.ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES__FK_ALLOWED_SPECIES_TO_ALLOWED_PROCEDURES_ALLOWED_PROCEDURES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSpeciesToAllowedProcedures as(String alias) {
        return new AllowedSpeciesToAllowedProcedures(alias, this);
    }

    /**
     * Rename this table
     */
    public AllowedSpeciesToAllowedProcedures rename(String name) {
        return new AllowedSpeciesToAllowedProcedures(name, null);
    }
}
