/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.CardInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardInfo extends TableImpl<CardInfoRecord> {

    private static final long serialVersionUID = 1539988962;

    /**
     * The reference instance of <code>wnprc_compliance.card_info</code>
     */
    public static final CardInfo CARD_INFO = new CardInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardInfoRecord> getRecordType() {
        return CardInfoRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.card_info.report_id</code>.
     */
    public final TableField<CardInfoRecord, String> REPORT_ID = createField("report_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.card_info.card_id</code>.
     */
    public final TableField<CardInfoRecord, String> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.card_info.first_name</code>.
     */
    public final TableField<CardInfoRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.last_name</code>.
     */
    public final TableField<CardInfoRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.middle_name</code>.
     */
    public final TableField<CardInfoRecord, String> MIDDLE_NAME = createField("middle_name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.department</code>.
     */
    public final TableField<CardInfoRecord, String> DEPARTMENT = createField("department", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.employee_number</code>.
     */
    public final TableField<CardInfoRecord, String> EMPLOYEE_NUMBER = createField("employee_number", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.info2</code>.
     */
    public final TableField<CardInfoRecord, String> INFO2 = createField("info2", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.info3</code>.
     */
    public final TableField<CardInfoRecord, String> INFO3 = createField("info3", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.info5</code>.
     */
    public final TableField<CardInfoRecord, String> INFO5 = createField("info5", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.container</code>.
     */
    public final TableField<CardInfoRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.card_info.createdby</code>.
     */
    public final TableField<CardInfoRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.created</code>.
     */
    public final TableField<CardInfoRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.modifiedby</code>.
     */
    public final TableField<CardInfoRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.card_info.modified</code>.
     */
    public final TableField<CardInfoRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.card_info</code> table reference
     */
    public CardInfo() {
        this("card_info", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.card_info</code> table reference
     */
    public CardInfo(String alias) {
        this(alias, CARD_INFO);
    }

    private CardInfo(String alias, Table<CardInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private CardInfo(String alias, Table<CardInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CardInfoRecord> getPrimaryKey() {
        return Keys.PK_CARD_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CardInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<CardInfoRecord>>asList(Keys.PK_CARD_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CardInfoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CardInfoRecord, ?>>asList(Keys.CARD_INFO__FK_CARD_INFO_ACCESS_REPORTS, Keys.CARD_INFO__FK_CARD_INFO_CARDS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardInfo as(String alias) {
        return new CardInfo(alias, this);
    }

    /**
     * Rename this table
     */
    public CardInfo rename(String name) {
        return new CardInfo(name, null);
    }
}
