/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.ProtocolRevisionsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtocolRevisions extends TableImpl<ProtocolRevisionsRecord> {

    private static final long serialVersionUID = 352860769;

    /**
     * The reference instance of <code>wnprc_compliance.protocol_revisions</code>
     */
    public static final ProtocolRevisions PROTOCOL_REVISIONS = new ProtocolRevisions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProtocolRevisionsRecord> getRecordType() {
        return ProtocolRevisionsRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.protocol_revisions.id</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.protocol_id</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> PROTOCOL_ID = createField("protocol_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.principal_investigator_id</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> PRINCIPAL_INVESTIGATOR_ID = createField("principal_investigator_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.spi_primary_id</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> SPI_PRIMARY_ID = createField("spi_primary_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.spi_secondary_id</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> SPI_SECONDARY_ID = createField("spi_secondary_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.approval_date</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Timestamp> APPROVAL_DATE = createField("approval_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.attached_file_id</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> ATTACHED_FILE_ID = createField("attached_file_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_biological_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_BIOLOGICAL_HAZARDS = createField("has_biological_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_chemical_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_CHEMICAL_HAZARDS = createField("has_chemical_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_physical_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_PHYSICAL_HAZARDS = createField("has_physical_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_radiation_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_RADIATION_HAZARDS = createField("has_radiation_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_wildlife_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_WILDLIFE_HAZARDS = createField("has_wildlife_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_other_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_OTHER_HAZARDS = createField("has_other_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.other_hazards_notes</code>.
     */
    public final TableField<ProtocolRevisionsRecord, String> OTHER_HAZARDS_NOTES = createField("other_hazards_notes", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.has_recombinant_material_hazards</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> HAS_RECOMBINANT_MATERIAL_HAZARDS = createField("has_recombinant_material_hazards", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.involves_euthanasia</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> INVOLVES_EUTHANASIA = createField("involves_euthanasia", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.allows_single_housing</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Boolean> ALLOWS_SINGLE_HOUSING = createField("allows_single_housing", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.createdby</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.created</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.modifiedby</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.protocol_revisions.modified</code>.
     */
    public final TableField<ProtocolRevisionsRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.protocol_revisions</code> table reference
     */
    public ProtocolRevisions() {
        this("protocol_revisions", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.protocol_revisions</code> table reference
     */
    public ProtocolRevisions(String alias) {
        this(alias, PROTOCOL_REVISIONS);
    }

    private ProtocolRevisions(String alias, Table<ProtocolRevisionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProtocolRevisions(String alias, Table<ProtocolRevisionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProtocolRevisionsRecord> getPrimaryKey() {
        return Keys.PK_PROTOCOL_REVISIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProtocolRevisionsRecord>> getKeys() {
        return Arrays.<UniqueKey<ProtocolRevisionsRecord>>asList(Keys.PK_PROTOCOL_REVISIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProtocolRevisionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProtocolRevisionsRecord, ?>>asList(Keys.PROTOCOL_REVISIONS__FK_PROTOCOL_REVISIONS_PROTOCOLS, Keys.PROTOCOL_REVISIONS__FK_PROTOCOL_REVISIONS_PI_PERSONS, Keys.PROTOCOL_REVISIONS__FK_PROTOCOL_REVISIONS_SPI1_PERSONS, Keys.PROTOCOL_REVISIONS__FK_PROTOCOL_REVISIONS_SPI2_PERSONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRevisions as(String alias) {
        return new ProtocolRevisions(alias, this);
    }

    /**
     * Rename this table
     */
    public ProtocolRevisions rename(String name) {
        return new ProtocolRevisions(name, null);
    }
}
