/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.ProtocolsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Protocols extends TableImpl<ProtocolsRecord> {

    private static final long serialVersionUID = -1007205713;

    /**
     * The reference instance of <code>wnprc_compliance.protocols</code>
     */
    public static final Protocols PROTOCOLS = new Protocols();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProtocolsRecord> getRecordType() {
        return ProtocolsRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.protocols.id</code>.
     */
    public final TableField<ProtocolsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.protocols.protocol_number</code>.
     */
    public final TableField<ProtocolsRecord, String> PROTOCOL_NUMBER = createField("protocol_number", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.protocols.container</code>.
     */
    public final TableField<ProtocolsRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.protocols.createdby</code>.
     */
    public final TableField<ProtocolsRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.protocols.created</code>.
     */
    public final TableField<ProtocolsRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.protocols.modifiedby</code>.
     */
    public final TableField<ProtocolsRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.protocols.modified</code>.
     */
    public final TableField<ProtocolsRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.protocols</code> table reference
     */
    public Protocols() {
        this("protocols", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.protocols</code> table reference
     */
    public Protocols(String alias) {
        this(alias, PROTOCOLS);
    }

    private Protocols(String alias, Table<ProtocolsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Protocols(String alias, Table<ProtocolsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProtocolsRecord> getPrimaryKey() {
        return Keys.PK_PROTOCOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProtocolsRecord>> getKeys() {
        return Arrays.<UniqueKey<ProtocolsRecord>>asList(Keys.PK_PROTOCOL, Keys.PROTOCOLS_PROTOCOL_NUMBER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Protocols as(String alias) {
        return new Protocols(alias, this);
    }

    /**
     * Rename this table
     */
    public Protocols rename(String name) {
        return new Protocols(name, null);
    }
}
