/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.TbClearancesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbClearances extends TableImpl<TbClearancesRecord> {

    private static final long serialVersionUID = 1878806879;

    /**
     * The reference instance of <code>wnprc_compliance.tb_clearances</code>
     */
    public static final TbClearances TB_CLEARANCES = new TbClearances();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbClearancesRecord> getRecordType() {
        return TbClearancesRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.tb_clearances.id</code>.
     */
    public final TableField<TbClearancesRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.date</code>.
     */
    public final TableField<TbClearancesRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.comment</code>.
     */
    public final TableField<TbClearancesRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.container</code>.
     */
    public final TableField<TbClearancesRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.createdby</code>.
     */
    public final TableField<TbClearancesRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.created</code>.
     */
    public final TableField<TbClearancesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.modifiedby</code>.
     */
    public final TableField<TbClearancesRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.tb_clearances.modified</code>.
     */
    public final TableField<TbClearancesRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.tb_clearances</code> table reference
     */
    public TbClearances() {
        this("tb_clearances", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.tb_clearances</code> table reference
     */
    public TbClearances(String alias) {
        this(alias, TB_CLEARANCES);
    }

    private TbClearances(String alias, Table<TbClearancesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbClearances(String alias, Table<TbClearancesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbClearancesRecord> getPrimaryKey() {
        return Keys.PK_TB_CLEARANCES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbClearancesRecord>> getKeys() {
        return Arrays.<UniqueKey<TbClearancesRecord>>asList(Keys.PK_TB_CLEARANCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbClearances as(String alias) {
        return new TbClearances(alias, this);
    }

    /**
     * Rename this table
     */
    public TbClearances rename(String name) {
        return new TbClearances(name, null);
    }
}
