version: "3.5"
networks:
  network1:
    driver: bridge
    name: sharedservices

services:

  postgres:
    image: postgres:$PG_VERSION
    container_name: postgres
    shm_size: 4g
    restart: always
    volumes:
      - "${PG_CONF_FILE}:/conf/postgresql.conf"
      - "${PG_DATA_DIR}:/var/lib/postgresql/data"
      - "${PG_HBA_FILE}:/conf/pg_hba.conf"
      - "${PG_LOG_DIR}:/logs"
    ports:
      - "${PG_PORT}:5432"
    expose:
      - "5432"
    networks:
      - network1
    environment:
      TZ: America/Chicago
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    command: postgres -c log_directory=/logs -c config_file=/conf/postgresql.conf -c hba_file=/conf/pg_hba.conf
    stop_signal: SIGTERM
    stop_grace_period: "120s"

  mailcatcher:
    image: schickling/mailcatcher:master
    networks:
      - network1
    environment:
      TZ: America/Chicago

  mailserver:
    image: wnprcehr/postfix:$POSTFIX_VERSION
    depends_on:
      - "mailcatcher"
    volumes:
      - "${NGINX_SERVER_CER_FILE}:/etc/postfix/certs/ehr.pem"
      - "${NGINX_SERVER_KEY_FILE}:/etc/postfix/certs/ehr.key"
    environment:
      MAIL_SERVER:
      TZ: America/Chicago
    expose:
      - "1025"
    networks:
      - network1

  labkey:
    image: wnprcehr/labkeysnapshot:$LK_VERSION
    container_name: labkey
    depends_on:
      - "mailserver"
      - "postgres"
    volumes:
      - "${LK_FILES_DIR}:/space/files"
      - "${LK_LOG_DIR}:/usr/local/tomcat/logs"
      - "${LK_MODULE_DEPLOY_DIR}:/usr/local/modules"
      - "${LK_SESSION_DIR}:/usr/local/labkey/sessions"
    expose:
      - "8080"
    networks:
      - network1
    environment:
      CATALINA_OPTS:
      JAVA_OPTS: "${LK_JAVA_OPTS} -Djdbc.user=${PG_USER} -Djdbc.pass=${PG_PASS} -Djdbc.url=jdbc:postgresql://postgres:5432/${PG_NAME} \
                  -Dmsql.user=${LK_MSQL_USER} -Dmsql.pass=${LK_MSQL_PASS} -Dmsql.url=\"${LK_MSQL_URL}\" \
                  -Dlabkey.masterEncryptionKey=${LK_MASTER_ENCRYPTION_KEY} \
		          -Darrow.user=${LK_ARROW_USER} -Darrow.pass=${LK_ARROW_PASS} -Darrow.url=\"${LK_ARROW_URL}\" \
                  -Dlog4j2.formatMsgNoLookups=true -Dserver.email.address=${SERVER_EMAIL_ADDRESS}"
      LK_BACKGROUND_USER: ${LK_BACKGROUND_USER}
      LK_BACKGROUND_USER_PASSWORD: ${LK_BACKGROUND_USER_PASSWORD}
      LK_BASE_URL: ${LK_BASE_URL}
      PG_NAME:
      PG_PASS:
      PG_USER:
      TZ: America/Chicago

  nginx:
    image: nginx:1.18.0
    depends_on:
      - "labkey"
    volumes:
      - "${NGINX_CLIENT_CER_FILE}:/usr/local/ssl/client-ca.pem"
      - "${NGINX_CLIENT_CRL_FILE}:/usr/local/ssl/crl.pem"
      - "${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf"
      - "${NGINX_SERVER_CER_FILE}:/usr/local/ssl/cert.pem"
      - "${NGINX_SERVER_PASS_FILE}:/usr/local/ssl/key.pass"
      - "${NGINX_SERVER_KEY_FILE}:/usr/local/ssl/key.pem"
      - "${NGINX_WELL_KNOWN_DIR}:/usr/share/nginx/html"
      - "${MAIL_CATCHER_HTPASSWD_FILE}:/etc/nginx/.htpasswd"
    ports:
      - "${LK_DANGER_PORT}:80"
      - "${LK_SECURE_PORT}:443"
      - "${MAIL_CATCHER_PORT}:1080"
      - "${CADVISOR_PORT}:8080"
    networks:
      - network1
    environment:
      TZ: America/Chicago

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    depends_on:
      - "postgres"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - network1
