version: "3.5"
networks:
  network1:
    driver: bridge
    name: sharedservices

services:

  postgres:
    image: postgres:9.4
    volumes:
      - "${PG_CONF_FILE}:/conf/postgresql.conf"
      - "${PG_DATA_DIR}:/var/lib/postgresql/data"
      - "${PG_HBA_FILE}:/conf/pg_hba.conf"
      - "${PG_LOG_DIR}:/logs"
    ports:
      - "${PG_PORT}:5432"
    expose:
      - "5432"
    networks:
      - network1
    environment:
      TZ: America/Chicago
    command: postgres -c log_directory=/logs -c config_file=/conf/postgresql.conf -c hba_file=/conf/pg_hba.conf
    stop_signal: SIGTERM
    stop_grace_period: "120s"

  mailcatcher:
    image: schickling/mailcatcher
    networks:
      - network1
    environment:
      TZ: America/Chicago

  mailserver:
    image: wnprcehr/postfix:latest
    depends_on:
      - "mailcatcher"
    environment:
      MAIL_SERVER:
      TZ: America/Chicago
    expose:
      - "1025"
    networks:
      - network1

  labkey:
    image: wnprcehr/labkey:17.2
    depends_on:
      - "mailserver"
      - "postgres"
    volumes:
      - "${LABKEY_FILES_DIR}:/backups/new_files_dir"
      - "${LABKEY_LOG_DIR}:/usr/local/tomcat/logs"
      - "${LABKEY_MODULE_DEPLOY_DIR}:/usr/local/modules"
      - "${LABKEY_SESSION_DIR}:/usr/local/labkey/sessions"
    expose:
      - "8080"
    networks:
      - network1
    environment:
      CATALINA_OPTS:
      JAVA_OPTS: "${JAVA_OPTS} -Djdbc.user=${PG_USER} -Djdbc.pass=${PG_PASS} -Djdbc.url=jdbc:postgresql://postgres:5432/${PG_NAME} \
                  -Dmsql.user=${MSQL_USER} -Dmsql.pass=${MSQL_PASS} -Dmsql.url=${MSQL_URL}"
      LK_BACKGROUND_USER:
      LK_BACKGROUND_USER_PASSWORD:
      LK_BASE_URL:
      PG_NAME:
      PG_PASS:
      PG_USER:
      TZ: America/Chicago

  nginx:
    image: nginx:1.13.0
    depends_on:
      - "labkey"
    volumes:
      - "${NGINX_CLIENT_CER_FILE}:/usr/local/ssl/client-ca.pem"
      - "${NGINX_CLIENT_CRL_FILE}:/usr/local/ssl/crl.pem"
      - "${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf"
      - "${NGINX_SERVER_CER_FILE}:/usr/local/ssl/cert.pem"
      - "${NGINX_SERVER_PASS_FILE}:/usr/local/ssl/key.pass"
      - "${NGINX_SERVER_KEY_FILE}:/usr/local/ssl/key.pem"
      - "${NGINX_WELL_KNOWN_DIR}:/usr/share/nginx/html"
      - "${MAIL_CATCHER_HTPASSWD_FILE}:/etc/nginx/.htpasswd"
    ports:
      - "${LABKEY_DANGER_PORT}:80"
      - "${LABKEY_SECURE_PORT}:443"
      - "${MAIL_CATCHER_PORT}:1080"
      - "${CADVISOR_PORT}:8080"
    networks:
      - network1
    environment:
      TZ: America/Chicago

  cadvisor:
    image: google/cadvisor:latest
    depends_on:
      - "postgres"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - network1
