version: "3"
services:
  db:
    image: postgres:9.6
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "8081:5432"
  labkey:
    image: labkey:17.2
    depends_on:
      - "db"
    volumes:
      - "../build/modules:/usr/local/labkey/externalModules"
    ports: 
      - "8080:8080"
    environment:
      - CATALINA_OPTS
