version: "3"
services:

  postgres:
    image: postgres:9.2
    volumes:
      - "${PG_DATA_DIR}:/var/lib/postgresql/data"
      - "${PG_CONF_FILE}:/var/lib/postgresql/data/postgresql.conf"
    ports:
      - "9081:5432"
    expose:
      - "5432"
    environment:
      TZ: America/Chicago

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      TZ: America/Chicago
    
  mailserver:
    image: wnprcehr/postfix:v0.1.0
    depends_on:
      - "mailcatcher"
    environment:
      MAIL_SERVER:
      TZ: America/Chicago
    ports:
      - "1025:1025"

  labkey:
    image: wnprcehr/labkey:15.2
    depends_on:
      - "mailserver"
      - "postgres"
    volumes:
      - "${LABKEY_FILES_DIR}:/usr/local/labkey/files"
      - "${LABKEY_LOG_DIR}:/usr/local/tomcat/logs"
      - "${LABKEY_MODULE_DEPLOY_DIR}:/usr/local/labkey/externalModules"
      - "${LABKEY_SESSION_DIR}:/usr/local/labkey/sessions"
    ports: 
      - "9080:8080"
    expose:
      - "8080"
    environment:
      CATALINA_OPTS:
      JAVA_OPTS: "${JAVA_OPTS} -Djdbc.user=${PG_USER} -Djdbc.pass=${PG_PASS} -Djdbc.url=jdbc:postgresql://postgres:5432/${PG_NAME}"
      PG_NAME:
      PG_PASS:
      PG_USER:

  nginx:
    image: nginx:1.13.0
    depends_on:
      - "labkey"
    volumes:
      - "${NGINX_CLIENT_CER_FILE}:/usr/local/ssl/client-ca.pem"
      - "${NGINX_CLIENT_CRL_FILE}:/usr/local/ssl/crl.pem"
      - "${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf"
      - "${NGINX_SERVER_CER_FILE}:/usr/local/ssl/cert.pem"
      - "${NGINX_SERVER_KEY_FILE}:/usr/local/ssl/key.pem"
      - "${NGINX_WELL_KNOWN_DIR}:/usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
    environment:
      TZ: America/Chicago

  perlscripts:
    image: wnprcehr/ehrcron:v0.1.0
    depends_on:
      - "labkey"
    volumes:
      - "${BACKUP_DIR}:/backups"
    environment:
      LK_BACKGROUND_USER: 
      LK_BACKGROUND_USER_PASSWORD:
      TZ: America/Chicago

  monit:
    image: wnprcehr/monit:latest
    depends_on:
      - "mailserver"
      - "postgres"
    links:
      - mailserver:mailserver-container
      - postgres
    volumes:
      - "${MONIT_CONFIG_FILE}:/etc/monit/monitrc"
      - "${MONIT_HOST_BACKUP_DIR}:/host/backup"
      - "${MONIT_HOST_ROOT_DIR}:/host"
      - "${MONIT_LOG_DIR}:/etc/monit/logs"
    environment:
      TZ: America/Chicago
