version: "3.5"

services:
  perlscripts:
    image: wnprcehr/ehrcron$PERL_PROD:$LABKEY_VERSION
    depends_on:
      - "labkey"
    volumes:
      - "${BACKUP_DIR}:/backups"
      - "${PRIMATEFS_DIR}:/mnt/IT-Backups/"
      - "${PG_DUMP_DIR}:/usr/local/postgresql/bin"
    networks:
      - network1
    environment:
      BACKUP_PG_NAME: "${BACKUP_PG_NAME}"
      BACKUP_PG_USER: "${BACKUP_PG_USER}"
      LK_BACKGROUND_USER:
      LK_BACKGROUND_USER_PASSWORD:
      LK_BASE_URL: "${LK_BASE_URL}"
      TZ: America/Chicago
