version: "3"
services:

  postgres:
    image: postgres:9.4
    volumes:
      - "${PG_DATA_DIR}:/var/lib/postgresql/data"
    ports:
      - "9081:5432"
    environment:
      TZ: America/Chicago
    
  labkey:
    image: labkey:15.2
    depends_on:
      - "postgres"
    volumes:
      - "${LABKEY_MODULE_DEPLOY_DIR}:/usr/local/labkey/externalModules"
    ports: 
      - "9080:8080"
    environment:
      CATALINA_OPTS:
      JAVA_OPTS: "${JAVA_OPTS} -Djdbc.user=${PG_USER} -Djdbc.pass=${PG_PASS} -Djdbc.url=jdbc:postgresql://postgres:5432/${PG_NAME}"
      PG_NAME:
      PG_PASS:
      PG_USER:
