version: "3.5"

services:
  perlscripts:
    image: wnprcehr/ehrcron:latest
    depends_on:
      - "labkey"
    volumes:
      - "${BACKUP_DIR}:/backups"
      - "${PRIMATEFS_DIR}:/mnt/IT-Backups/"
      - "${PG_DUMP_DIR}:/usr/lib/postgresql/11/bin"
    networks:
      - network1
    environment:
      LK_BACKGROUND_USER:
      LK_BACKGROUND_USER_PASSWORD:
      LK_BASE_URL:
      TZ: America/Chicago
