#!/bin/bash

GIT_HUB_TAG="docker/$DOCKER_TAG"

WNPRC_REPO="wnprcehr/labkey"
LK_VERSION=""

PROD_REGEX="^([0-9]{2}\.[0-9]{1,2})_refs_heads_release([0-9]{2}\.[0-9]{1,2})-SNAPSHOT"
FB_REGEX="^([0-9]{2}\.[0-9]{1,2})_(.*)"

if [[ $DOCKER_TAG =~ $PROD_REGEX ]]
then
    echo "Pushing image to SNAPSHOT repo, version " ${BASH_REMATCH[1]}
    #WNPRC_REPO+=snapshot
    docker tag $IMAGE_NAME "wnprcehr/labkeysnapshot:"${BASH_REMATCH[1]}
    docker push "wnprcehr/labkeysnapshot":${BASH_REMATCH[1]}

elif [[ $DOCKER_TAG =~ $FB_REGEX  ]]
then
    echo "Push image to Docker repo ${WNPRC_REPPO} with tag ${BASH_REMATCH[1]}_${BASH_REMATCH[2]}"
    docker tag $IMAGE_NAME "wnprcehr/labkey:"${BASH_REMATCH[1]}_${BASH_REMATCH[2]}
    docker push "wnprcehr/labkey:"${BASH_REMATCH[1]}_${BASH_REMATCH[2]}

else
    echo "Pushing develop branch"
    docker tag $IMAGE_NAME "wnprcehr/labkey:"${BASH_REMATCH[1]}_develop
    docker push "wnprcehr/labkey:"${BASH_REMATCH[1]}_develop

fi

#docker tag $IMAGE_NAME $WNPRC_REPO:${BASH_REMATCH[1]}_${DOCKER_TAG}
#docker push $WNPRC_REPO:${BASH_REMATCH[1]}

echo "Deleting following tag: $GIT_HUB_TAG"
git push --delete origin $GIT_HUB_TAG