/**
 * This class is generated by jOOQ
 */
package org.labkey.gringotts.model.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.gringotts.model.jooq.tables.VaultLinks;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VaultLinksRecord extends UpdatableRecordImpl<VaultLinksRecord> implements Record8<String, String, String, String, String, String, Boolean, Integer> {

    private static final long serialVersionUID = -783416194;

    /**
     * Setter for <code>gringotts.vault_links.vaultid1</code>.
     */
    public void setVaultid1(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.vaultid1</code>.
     */
    public String getVaultid1() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gringotts.vault_links.columnid</code>.
     */
    public void setColumnid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.columnid</code>.
     */
    public String getColumnid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gringotts.vault_links.vaultid2</code>.
     */
    public void setVaultid2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.vaultid2</code>.
     */
    public String getVaultid2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gringotts.vault_links.record1</code>.
     */
    public void setRecord1(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.record1</code>.
     */
    public String getRecord1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gringotts.vault_links.record2</code>.
     */
    public void setRecord2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.record2</code>.
     */
    public String getRecord2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gringotts.vault_links.transactionid</code>.
     */
    public void setTransactionid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.transactionid</code>.
     */
    public String getTransactionid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gringotts.vault_links.islinked</code>.
     */
    public void setIslinked(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.islinked</code>.
     */
    public Boolean getIslinked() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>gringotts.vault_links.order</code>.
     */
    public void setOrder(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gringotts.vault_links.order</code>.
     */
    public Integer getOrder() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record6<String, String, String, String, String, String> key() {
        return (Record6) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Boolean, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Boolean, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return VaultLinks.VAULT_LINKS.VAULTID1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VaultLinks.VAULT_LINKS.COLUMNID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VaultLinks.VAULT_LINKS.VAULTID2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VaultLinks.VAULT_LINKS.RECORD1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VaultLinks.VAULT_LINKS.RECORD2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VaultLinks.VAULT_LINKS.TRANSACTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return VaultLinks.VAULT_LINKS.ISLINKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VaultLinks.VAULT_LINKS.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getVaultid1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getColumnid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getVaultid2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRecord1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRecord2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTransactionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getIslinked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value1(String value) {
        setVaultid1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value2(String value) {
        setColumnid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value3(String value) {
        setVaultid2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value4(String value) {
        setRecord1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value5(String value) {
        setRecord2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value6(String value) {
        setTransactionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value7(Boolean value) {
        setIslinked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord value8(Integer value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultLinksRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VaultLinksRecord
     */
    public VaultLinksRecord() {
        super(VaultLinks.VAULT_LINKS);
    }

    /**
     * Create a detached, initialised VaultLinksRecord
     */
    public VaultLinksRecord(String vaultid1, String columnid, String vaultid2, String record1, String record2, String transactionid, Boolean islinked, Integer order) {
        super(VaultLinks.VAULT_LINKS);

        set(0, vaultid1);
        set(1, columnid);
        set(2, vaultid2);
        set(3, record1);
        set(4, record2);
        set(5, transactionid);
        set(6, islinked);
        set(7, order);
    }
}
