/**
 * This class is generated by jOOQ
 */
package org.labkey.gringotts.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.gringotts.model.jooq.tables.Vaults;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VaultsRecord extends UpdatableRecordImpl<VaultsRecord> implements Record4<String, String, Integer, Timestamp> {

    private static final long serialVersionUID = 1723757199;

    /**
     * Setter for <code>gringotts.vaults.vaultid</code>.
     */
    public void setVaultid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gringotts.vaults.vaultid</code>.
     */
    public String getVaultid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gringotts.vaults.vaultclassname</code>.
     */
    public void setVaultclassname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gringotts.vaults.vaultclassname</code>.
     */
    public String getVaultclassname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gringotts.vaults.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gringotts.vaults.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gringotts.vaults.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>gringotts.vaults.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Timestamp> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Vaults.VAULTS.VAULTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Vaults.VAULTS.VAULTCLASSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Vaults.VAULTS.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Vaults.VAULTS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getVaultid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVaultclassname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultsRecord value1(String value) {
        setVaultid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultsRecord value2(String value) {
        setVaultclassname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultsRecord value3(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultsRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultsRecord values(String value1, String value2, Integer value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VaultsRecord
     */
    public VaultsRecord() {
        super(Vaults.VAULTS);
    }

    /**
     * Create a detached, initialised VaultsRecord
     */
    public VaultsRecord(String vaultid, String vaultclassname, Integer createdby, Timestamp created) {
        super(Vaults.VAULTS);

        set(0, vaultid);
        set(1, vaultclassname);
        set(2, createdby);
        set(3, created);
    }
}
