#!/bin/bash
#
# Copyright (c) 2009-2012 LabKey Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#assume that some process initialized from mysql has dumped text files. Those files should be
#generated by a command like this:
#
# mysqldump -u username --password=xxxx --tab=$MYSQL_DUMPDIR --no-create-info colony --ignore-table=tmp_table
#
# Note that MYSQL_DUMPDIR in that case must be relative to the mysql SERVER, as the server
# itself is dumping the files
#
# DUMPDIR as a directory relative to THIS script. Change following line:
#
DUMPDIR=/Users/bimber/mysql-dump
FIXEDDIR=/Users/bimber/mysql-dump

POSTGRES_DB=labkey

#
# Iterate over the dumped dataset files.
for dumpfile in $DUMPDIR/datasets/*.tsv
do
  fname=${dumpfile##*/}
  basename=${fname%%.*} 

#      java FixTabs < $dumpfile > ${FIXEDDIR}/datasets/$fname
#      if [ $? -ne 0 ]; then
#         echo "Error fixing $fname" >&2
#         exit 1
#      fi

      echo "psql TRUNCATE col_dump.$basename" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "TRUNCATE col_dump.$basename;" 
      if [ $? -ne 0 ]; then
         echo "Error truncating col_dump.$basename; Perhaps security error?"  >&2
         exit 1
      fi

      echo "copy col_dump.$basename FROM ${FIXEDDIR}/datasets/$fname" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "\copy col_dump.$basename FROM '${FIXEDDIR}/datasets/$fname' delimiter as '\t' csv header"  
      if [ $? -ne 0 ]; then
         echo "Error copying data see errors.log for details" >&2
#         exit 1
      fi
  echo
done

# Iterate over the dumped lists.
for dumpfile in $DUMPDIR/lists/*.tsv
do
  fname=${dumpfile##*/}
  basename=${fname%%.*}
#      java FixTabs < $dumpfile > ${FIXEDDIR}/lists/$fname
#      if [ $? -ne 0 ]; then
#         echo "Error fixing $fname" >&2
#         exit 1
#      fi

      echo "psql TRUNCATE col_dump.$basename" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "TRUNCATE col_dump.$basename;" 
      if [ $? -ne 0 ]; then
         echo "Error truncating col_dump.$basename; Perhaps security error?"  >&2
         exit 1
      fi

      echo "copy col_dump.$basename FROM ${FIXEDDIR}/lists/$fname" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "\copy col_dump.$basename FROM '${FIXEDDIR}/lists/$fname' delimiter as '\t' csv header"  
      if [ $? -ne 0 ]; then
         echo "Error copying data see errors.log for details" >&2
         exit 1
      fi
  echo
done

echo "Load successful!"
exit 0
