/**
 * This class is generated by jOOQ
 */
package org.labkey.deviceproxy.model.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.deviceproxy.model.jooq.Deviceproxy;
import org.labkey.deviceproxy.model.jooq.Keys;
import org.labkey.deviceproxy.model.jooq.tables.records.DeviceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Device extends TableImpl<DeviceRecord> {

    private static final long serialVersionUID = -496230444;

    /**
     * The reference instance of <code>deviceproxy.device</code>
     */
    public static final Device DEVICE = new Device();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceRecord> getRecordType() {
        return DeviceRecord.class;
    }

    /**
     * The column <code>deviceproxy.device.public_key</code>.
     */
    public final TableField<DeviceRecord, String> PUBLIC_KEY = createField("public_key", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>deviceproxy.device.name</code>.
     */
    public final TableField<DeviceRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>deviceproxy.device.description</code>.
     */
    public final TableField<DeviceRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>deviceproxy.device</code> table reference
     */
    public Device() {
        this("device", null);
    }

    /**
     * Create an aliased <code>deviceproxy.device</code> table reference
     */
    public Device(String alias) {
        this(alias, DEVICE);
    }

    private Device(String alias, Table<DeviceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Device(String alias, Table<DeviceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Deviceproxy.DEVICEPROXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeviceRecord> getPrimaryKey() {
        return Keys.PK_DEVICE_REQUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeviceRecord>> getKeys() {
        return Arrays.<UniqueKey<DeviceRecord>>asList(Keys.PK_DEVICE_REQUEST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Device as(String alias) {
        return new Device(alias, this);
    }

    /**
     * Rename this table
     */
    public Device rename(String name) {
        return new Device(name, null);
    }
}
