/**
 * This class is generated by jOOQ
 */
package org.labkey.apikey.model.jooq.tables.records;


import jakarta.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.apikey.model.jooq.tables.AllowedServices;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedServicesRecord extends UpdatableRecordImpl<AllowedServicesRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1275932371;

    /**
     * Setter for <code>apikey.allowed_services.apikey</code>.
     */
    public void setApikey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>apikey.allowed_services.apikey</code>.
     */
    public String getApikey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>apikey.allowed_services.modulename</code>.
     */
    public void setModulename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>apikey.allowed_services.modulename</code>.
     */
    public String getModulename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>apikey.allowed_services.servicename</code>.
     */
    public void setServicename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>apikey.allowed_services.servicename</code>.
     */
    public String getServicename() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AllowedServices.ALLOWED_SERVICES.APIKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AllowedServices.ALLOWED_SERVICES.MODULENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AllowedServices.ALLOWED_SERVICES.SERVICENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getApikey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getModulename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getServicename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServicesRecord value1(String value) {
        setApikey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServicesRecord value2(String value) {
        setModulename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServicesRecord value3(String value) {
        setServicename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedServicesRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedServicesRecord
     */
    public AllowedServicesRecord() {
        super(AllowedServices.ALLOWED_SERVICES);
    }

    /**
     * Create a detached, initialised AllowedServicesRecord
     */
    public AllowedServicesRecord(String apikey, String modulename, String servicename) {
        super(AllowedServices.ALLOWED_SERVICES);

        set(0, apikey);
        set(1, modulename);
        set(2, servicename);
    }
}
