#!/bin/bash
#
# Copyright (c) 2009-2012 LabKey Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#assume that some process initialized from mysql has dumped text files. Those files should be
#generated by a command like this:
#
# mysqldump -u username --password=xxxx --tab=$MYSQL_DUMPDIR --no-create-info colony --ignore-table=tmp_table
#
# Note that MYSQL_DUMPDIR in that case must be relative to the mysql SERVER, as the server
# itself is dumping the files
#
# DUMPDIR as a directory relative to THIS script. Change following line:
#
DUMPDIR=primate-dump
FIXEDDIR=fixed

POSTGRES_DB=trunk
POSTGRES_PASS=sasa

#
# Iterate over the dumped text files.
for dumpfile in $DUMPDIR/*.txt
do
  fname=${dumpfile##*/}
  basename=${fname%%.*}
  echo "fixtabs $fname" 
  if [ ! -f ${FIXEDDIR}/$fname ]; then
      java FixTabs < $dumpfile > ${FIXEDDIR}/$fname
      if [ $? -ne 0 ]; then
         echo "Error fixing $fname" >&2
         exit 1
      fi

      echo "psql TRUNCATE colony.$basename" 
      psql -U postgres -d ${POSTGRES_DB} -c "TRUNCATE colony.$basename;" 
      if [ $? -ne 0 ]; then
         echo "Error truncating colony.$basename; Perhaps security error?"  >&2
         exit 1
      fi

      echo "copy colony.$basename FROM ${FIXEDDIR}/$fname" 
      psql -U postgres -d ${POSTGRES_DB} -c "\copy colony.$basename FROM '${FIXEDDIR}/$fname'"  
      if [ $? -ne 0 ]; then
         echo "Error copying data see errors.log for details" >&2
         exit 1
      fi
  fi
  echo
done

echo "Load successful!"
exit 0
