/**
 * This class is generated by jOOQ
 */
package org.labkey.gringotts.model.raw;


import javax.annotation.Generated;

import org.labkey.gringotts.model.raw.tables.Records;
import org.labkey.gringotts.model.raw.tables.Transactions;
import org.labkey.gringotts.model.raw.tables.VaultColumns;
import org.labkey.gringotts.model.raw.tables.VaultLinks;
import org.labkey.gringotts.model.raw.tables.VaultTextValues;
import org.labkey.gringotts.model.raw.tables.Vaults;


/**
 * Convenience access to all tables in gringotts
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>gringotts.records</code>.
     */
    public static final Records RECORDS = org.labkey.gringotts.model.raw.tables.Records.RECORDS;

    /**
     * The table <code>gringotts.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = org.labkey.gringotts.model.raw.tables.Transactions.TRANSACTIONS;

    /**
     * The table <code>gringotts.vault_columns</code>.
     */
    public static final VaultColumns VAULT_COLUMNS = org.labkey.gringotts.model.raw.tables.VaultColumns.VAULT_COLUMNS;

    /**
     * The table <code>gringotts.vault_links</code>.
     */
    public static final VaultLinks VAULT_LINKS = org.labkey.gringotts.model.raw.tables.VaultLinks.VAULT_LINKS;

    /**
     * The table <code>gringotts.vault_text_values</code>.
     */
    public static final VaultTextValues VAULT_TEXT_VALUES = org.labkey.gringotts.model.raw.tables.VaultTextValues.VAULT_TEXT_VALUES;

    /**
     * The table <code>gringotts.vaults</code>.
     */
    public static final Vaults VAULTS = org.labkey.gringotts.model.raw.tables.Vaults.VAULTS;
}
