/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.AccessReports;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessReportsRecord extends UpdatableRecordImpl<AccessReportsRecord> implements Record7<String, Timestamp, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -1442781073;

    /**
     * Setter for <code>wnprc_compliance.access_reports.report_id</code>.
     */
    public void setReportId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.report_id</code>.
     */
    public String getReportId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.access_reports.date</code>.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.access_reports.container</code>.
     */
    public void setContainer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.container</code>.
     */
    public String getContainer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.access_reports.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.access_reports.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.access_reports.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.access_reports.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.access_reports.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Timestamp, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Timestamp, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AccessReports.ACCESS_REPORTS.REPORT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return AccessReports.ACCESS_REPORTS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AccessReports.ACCESS_REPORTS.CONTAINER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return AccessReports.ACCESS_REPORTS.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return AccessReports.ACCESS_REPORTS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return AccessReports.ACCESS_REPORTS.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return AccessReports.ACCESS_REPORTS.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value1(String value) {
        setReportId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value3(String value) {
        setContainer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value4(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value6(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord value7(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportsRecord values(String value1, Timestamp value2, String value3, Integer value4, Timestamp value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccessReportsRecord
     */
    public AccessReportsRecord() {
        super(AccessReports.ACCESS_REPORTS);
    }

    /**
     * Create a detached, initialised AccessReportsRecord
     */
    public AccessReportsRecord(String reportId, Timestamp date, String container, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(AccessReports.ACCESS_REPORTS);

        set(0, reportId);
        set(1, date);
        set(2, container);
        set(3, createdby);
        set(4, created);
        set(5, modifiedby);
        set(6, modified);
    }
}
