/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.DrugRegimenFrequencyThreshold;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRegimenFrequencyThresholdRecord extends UpdatableRecordImpl<DrugRegimenFrequencyThresholdRecord> implements Record8<String, Integer, String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 331401547;

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.timeperiod</code>.
     */
    public void setTimeperiod(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.timeperiod</code>.
     */
    public Integer getTimeperiod() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.time_unit</code>.
     */
    public void setTimeUnit(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.time_unit</code>.
     */
    public String getTimeUnit() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimen_frequency_threshold.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimen_frequency_threshold.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Integer, String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Integer, String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.TIMEPERIOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.TIME_UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTimeperiod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTimeUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value2(Integer value) {
        setTimeperiod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value3(String value) {
        setTimeUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value5(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value6(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value7(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord value8(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThresholdRecord values(String value1, Integer value2, String value3, String value4, Integer value5, Timestamp value6, Integer value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrugRegimenFrequencyThresholdRecord
     */
    public DrugRegimenFrequencyThresholdRecord() {
        super(DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD);
    }

    /**
     * Create a detached, initialised DrugRegimenFrequencyThresholdRecord
     */
    public DrugRegimenFrequencyThresholdRecord(String id, Integer timeperiod, String timeUnit, String type, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(DrugRegimenFrequencyThreshold.DRUG_REGIMEN_FREQUENCY_THRESHOLD);

        set(0, id);
        set(1, timeperiod);
        set(2, timeUnit);
        set(3, type);
        set(4, createdby);
        set(5, created);
        set(6, modifiedby);
        set(7, modified);
    }
}
