/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.DrugRoutes;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRoutesRecord extends UpdatableRecordImpl<DrugRoutesRecord> implements Record6<String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = -1791549077;

    /**
     * Setter for <code>wnprc_compliance.drug_routes.drug_id</code>.
     */
    public void setDrugId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_routes.drug_id</code>.
     */
    public String getDrugId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_routes.route</code>.
     */
    public void setRoute(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_routes.route</code>.
     */
    public String getRoute() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_routes.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_routes.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_routes.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_routes.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_routes.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_routes.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_routes.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_routes.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DrugRoutes.DRUG_ROUTES.DRUG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DrugRoutes.DRUG_ROUTES.ROUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DrugRoutes.DRUG_ROUTES.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DrugRoutes.DRUG_ROUTES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DrugRoutes.DRUG_ROUTES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DrugRoutes.DRUG_ROUTES.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDrugId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord value1(String value) {
        setDrugId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord value2(String value) {
        setRoute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord value3(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord value5(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord value6(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutesRecord values(String value1, String value2, Integer value3, Timestamp value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrugRoutesRecord
     */
    public DrugRoutesRecord() {
        super(DrugRoutes.DRUG_ROUTES);
    }

    /**
     * Create a detached, initialised DrugRoutesRecord
     */
    public DrugRoutesRecord(String drugId, String route, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(DrugRoutes.DRUG_ROUTES);

        set(0, drugId);
        set(1, route);
        set(2, createdby);
        set(3, created);
        set(4, modifiedby);
        set(5, modified);
    }
}
