/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.DrugRegimensToAllowedProcedures;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRegimensToAllowedProceduresRecord extends UpdatableRecordImpl<DrugRegimensToAllowedProceduresRecord> implements Record7<String, String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 679437658;

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.protocol_revision_id</code>.
     */
    public void setProtocolRevisionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.protocol_revision_id</code>.
     */
    public String getProtocolRevisionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.species_classifier</code>.
     */
    public void setSpeciesClassifier(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.species_classifier</code>.
     */
    public String getSpeciesClassifier() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.drug_regimen_id</code>.
     */
    public void setDrugRegimenId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.drug_regimen_id</code>.
     */
    public String getDrugRegimenId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.drug_regimens_to_allowed_procedures.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.PROTOCOL_REVISION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.SPECIES_CLASSIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.DRUG_REGIMEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProtocolRevisionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpeciesClassifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDrugRegimenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value1(String value) {
        setProtocolRevisionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value2(String value) {
        setSpeciesClassifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value3(String value) {
        setDrugRegimenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value4(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value6(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord value7(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimensToAllowedProceduresRecord values(String value1, String value2, String value3, Integer value4, Timestamp value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrugRegimensToAllowedProceduresRecord
     */
    public DrugRegimensToAllowedProceduresRecord() {
        super(DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES);
    }

    /**
     * Create a detached, initialised DrugRegimensToAllowedProceduresRecord
     */
    public DrugRegimensToAllowedProceduresRecord(String protocolRevisionId, String speciesClassifier, String drugRegimenId, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(DrugRegimensToAllowedProcedures.DRUG_REGIMENS_TO_ALLOWED_PROCEDURES);

        set(0, protocolRevisionId);
        set(1, speciesClassifier);
        set(2, drugRegimenId);
        set(3, createdby);
        set(4, created);
        set(5, modifiedby);
        set(6, modified);
    }
}
