/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.PendingTbClearances;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PendingTbClearancesRecord extends UpdatableRecordImpl<PendingTbClearancesRecord> implements Record10<String, Timestamp, String, String, Boolean, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 1314936889;

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.date</code>.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.comment</code>.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.comment</code>.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.tbclearance_id</code>.
     */
    public void setTbclearanceId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.tbclearance_id</code>.
     */
    public String getTbclearanceId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.archived</code>.
     */
    public void setArchived(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.archived</code>.
     */
    public Boolean getArchived() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.container</code>.
     */
    public void setContainer(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.container</code>.
     */
    public String getContainer() {
        return (String) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>wnprc_compliance.pending_tb_clearances.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>wnprc_compliance.pending_tb_clearances.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Timestamp, String, String, Boolean, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Timestamp, String, String, Boolean, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.TBCLEARANCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.ARCHIVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.CONTAINER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return PendingTbClearances.PENDING_TB_CLEARANCES.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTbclearanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getArchived();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value3(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value4(String value) {
        setTbclearanceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value5(Boolean value) {
        setArchived(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value6(String value) {
        setContainer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value7(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value8(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value9(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord value10(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearancesRecord values(String value1, Timestamp value2, String value3, String value4, Boolean value5, String value6, Integer value7, Timestamp value8, Integer value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PendingTbClearancesRecord
     */
    public PendingTbClearancesRecord() {
        super(PendingTbClearances.PENDING_TB_CLEARANCES);
    }

    /**
     * Create a detached, initialised PendingTbClearancesRecord
     */
    public PendingTbClearancesRecord(String id, Timestamp date, String comment, String tbclearanceId, Boolean archived, String container, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(PendingTbClearances.PENDING_TB_CLEARANCES);

        set(0, id);
        set(1, date);
        set(2, comment);
        set(3, tbclearanceId);
        set(4, archived);
        set(5, container);
        set(6, createdby);
        set(7, created);
        set(8, modifiedby);
        set(9, modified);
    }
}
