/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.labkey.wnprc_compliance.model.jooq.tables.Protocols;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtocolsRecord extends UpdatableRecordImpl<ProtocolsRecord> implements Record7<String, String, String, Integer, Timestamp, Integer, Timestamp> {

    private static final long serialVersionUID = 1211749762;

    /**
     * Setter for <code>wnprc_compliance.protocols.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wnprc_compliance.protocols.protocol_number</code>.
     */
    public void setProtocolNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.protocol_number</code>.
     */
    public String getProtocolNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wnprc_compliance.protocols.container</code>.
     */
    public void setContainer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.container</code>.
     */
    public String getContainer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wnprc_compliance.protocols.createdby</code>.
     */
    public void setCreatedby(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.createdby</code>.
     */
    public Integer getCreatedby() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>wnprc_compliance.protocols.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>wnprc_compliance.protocols.modifiedby</code>.
     */
    public void setModifiedby(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.modifiedby</code>.
     */
    public Integer getModifiedby() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>wnprc_compliance.protocols.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>wnprc_compliance.protocols.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, Timestamp, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Protocols.PROTOCOLS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Protocols.PROTOCOLS.PROTOCOL_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Protocols.PROTOCOLS.CONTAINER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Protocols.PROTOCOLS.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Protocols.PROTOCOLS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Protocols.PROTOCOLS.MODIFIEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Protocols.PROTOCOLS.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProtocolNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContainer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value2(String value) {
        setProtocolNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value3(String value) {
        setContainer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value4(Integer value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value6(Integer value) {
        setModifiedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord value7(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolsRecord values(String value1, String value2, String value3, Integer value4, Timestamp value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtocolsRecord
     */
    public ProtocolsRecord() {
        super(Protocols.PROTOCOLS);
    }

    /**
     * Create a detached, initialised ProtocolsRecord
     */
    public ProtocolsRecord(String id, String protocolNumber, String container, Integer createdby, Timestamp created, Integer modifiedby, Timestamp modified) {
        super(Protocols.PROTOCOLS);

        set(0, id);
        set(1, protocolNumber);
        set(2, container);
        set(3, createdby);
        set(4, created);
        set(5, modifiedby);
        set(6, modified);
    }
}
