/**
 * This class is generated by jOOQ
 */
package org.labkey.gringotts.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.gringotts.model.jooq.Gringotts;
import org.labkey.gringotts.model.jooq.Keys;
import org.labkey.gringotts.model.jooq.tables.records.VaultDatetimeValuesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VaultDatetimeValues extends TableImpl<VaultDatetimeValuesRecord> {

    private static final long serialVersionUID = 273910346;

    /**
     * The reference instance of <code>gringotts.vault_datetime_values</code>
     */
    public static final VaultDatetimeValues VAULT_DATETIME_VALUES = new VaultDatetimeValues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VaultDatetimeValuesRecord> getRecordType() {
        return VaultDatetimeValuesRecord.class;
    }

    /**
     * The column <code>gringotts.vault_datetime_values.vaultid</code>.
     */
    public final TableField<VaultDatetimeValuesRecord, String> VAULTID = createField("vaultid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gringotts.vault_datetime_values.recordid</code>.
     */
    public final TableField<VaultDatetimeValuesRecord, String> RECORDID = createField("recordid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gringotts.vault_datetime_values.columnid</code>.
     */
    public final TableField<VaultDatetimeValuesRecord, String> COLUMNID = createField("columnid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gringotts.vault_datetime_values.transactionid</code>.
     */
    public final TableField<VaultDatetimeValuesRecord, String> TRANSACTIONID = createField("transactionid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gringotts.vault_datetime_values.value</code>.
     */
    public final TableField<VaultDatetimeValuesRecord, Timestamp> VALUE = createField("value", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>gringotts.vault_datetime_values</code> table reference
     */
    public VaultDatetimeValues() {
        this("vault_datetime_values", null);
    }

    /**
     * Create an aliased <code>gringotts.vault_datetime_values</code> table reference
     */
    public VaultDatetimeValues(String alias) {
        this(alias, VAULT_DATETIME_VALUES);
    }

    private VaultDatetimeValues(String alias, Table<VaultDatetimeValuesRecord> aliased) {
        this(alias, aliased, null);
    }

    private VaultDatetimeValues(String alias, Table<VaultDatetimeValuesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gringotts.GRINGOTTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VaultDatetimeValuesRecord> getPrimaryKey() {
        return Keys.PK_VAULT_DATETIME_VALUES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VaultDatetimeValuesRecord>> getKeys() {
        return Arrays.<UniqueKey<VaultDatetimeValuesRecord>>asList(Keys.PK_VAULT_DATETIME_VALUES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VaultDatetimeValuesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VaultDatetimeValuesRecord, ?>>asList(Keys.VAULT_DATETIME_VALUES__FK_VAULT_DATETIME_VALUES_TRANSACTIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VaultDatetimeValues as(String alias) {
        return new VaultDatetimeValues(alias, this);
    }

    /**
     * Rename this table
     */
    public VaultDatetimeValues rename(String name) {
        return new VaultDatetimeValues(name, null);
    }
}
