/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.AccessReportDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessReportData extends TableImpl<AccessReportDataRecord> {

    private static final long serialVersionUID = -1758768485;

    /**
     * The reference instance of <code>wnprc_compliance.access_report_data</code>
     */
    public static final AccessReportData ACCESS_REPORT_DATA = new AccessReportData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccessReportDataRecord> getRecordType() {
        return AccessReportDataRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.access_report_data.report_id</code>.
     */
    public final TableField<AccessReportDataRecord, String> REPORT_ID = createField("report_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.area</code>.
     */
    public final TableField<AccessReportDataRecord, String> AREA = createField("area", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.card_id</code>.
     */
    public final TableField<AccessReportDataRecord, String> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.schedule_pt</code>.
     */
    public final TableField<AccessReportDataRecord, String> SCHEDULE_PT = createField("schedule_pt", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.enabled</code>.
     */
    public final TableField<AccessReportDataRecord, Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.last_entered</code>.
     */
    public final TableField<AccessReportDataRecord, Timestamp> LAST_ENTERED = createField("last_entered", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.container</code>.
     */
    public final TableField<AccessReportDataRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.createdby</code>.
     */
    public final TableField<AccessReportDataRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.created</code>.
     */
    public final TableField<AccessReportDataRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.modifiedby</code>.
     */
    public final TableField<AccessReportDataRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.access_report_data.modified</code>.
     */
    public final TableField<AccessReportDataRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.access_report_data</code> table reference
     */
    public AccessReportData() {
        this("access_report_data", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.access_report_data</code> table reference
     */
    public AccessReportData(String alias) {
        this(alias, ACCESS_REPORT_DATA);
    }

    private AccessReportData(String alias, Table<AccessReportDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccessReportData(String alias, Table<AccessReportDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccessReportDataRecord> getPrimaryKey() {
        return Keys.PK_ACCESS_REPORT_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccessReportDataRecord>> getKeys() {
        return Arrays.<UniqueKey<AccessReportDataRecord>>asList(Keys.PK_ACCESS_REPORT_DATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AccessReportDataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AccessReportDataRecord, ?>>asList(Keys.ACCESS_REPORT_DATA__FK_ACCESS_REPORT_DATA_ACCESS_REPORTS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessReportData as(String alias) {
        return new AccessReportData(alias, this);
    }

    /**
     * Rename this table
     */
    public AccessReportData rename(String name) {
        return new AccessReportData(name, null);
    }
}
