/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.AllowedSurgeriesToDrugRegimensRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedSurgeriesToDrugRegimens extends TableImpl<AllowedSurgeriesToDrugRegimensRecord> {

    private static final long serialVersionUID = 680559963;

    /**
     * The reference instance of <code>wnprc_compliance.allowed_surgeries_to_drug_regimens</code>
     */
    public static final AllowedSurgeriesToDrugRegimens ALLOWED_SURGERIES_TO_DRUG_REGIMENS = new AllowedSurgeriesToDrugRegimens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AllowedSurgeriesToDrugRegimensRecord> getRecordType() {
        return AllowedSurgeriesToDrugRegimensRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.allowed_surgeries_to_drug_regimens.surgery_id</code>.
     */
    public final TableField<AllowedSurgeriesToDrugRegimensRecord, String> SURGERY_ID = createField("surgery_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.allowed_surgeries_to_drug_regimens.drug_regimen_id</code>.
     */
    public final TableField<AllowedSurgeriesToDrugRegimensRecord, String> DRUG_REGIMEN_ID = createField("drug_regimen_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.allowed_surgeries_to_drug_regimens.createdby</code>.
     */
    public final TableField<AllowedSurgeriesToDrugRegimensRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.allowed_surgeries_to_drug_regimens.created</code>.
     */
    public final TableField<AllowedSurgeriesToDrugRegimensRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.allowed_surgeries_to_drug_regimens.modifiedby</code>.
     */
    public final TableField<AllowedSurgeriesToDrugRegimensRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.allowed_surgeries_to_drug_regimens.modified</code>.
     */
    public final TableField<AllowedSurgeriesToDrugRegimensRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.allowed_surgeries_to_drug_regimens</code> table reference
     */
    public AllowedSurgeriesToDrugRegimens() {
        this("allowed_surgeries_to_drug_regimens", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.allowed_surgeries_to_drug_regimens</code> table reference
     */
    public AllowedSurgeriesToDrugRegimens(String alias) {
        this(alias, ALLOWED_SURGERIES_TO_DRUG_REGIMENS);
    }

    private AllowedSurgeriesToDrugRegimens(String alias, Table<AllowedSurgeriesToDrugRegimensRecord> aliased) {
        this(alias, aliased, null);
    }

    private AllowedSurgeriesToDrugRegimens(String alias, Table<AllowedSurgeriesToDrugRegimensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AllowedSurgeriesToDrugRegimensRecord> getPrimaryKey() {
        return Keys.PK_ALLOWED_SURGERIES_TO_DRUG_REGIMENS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AllowedSurgeriesToDrugRegimensRecord>> getKeys() {
        return Arrays.<UniqueKey<AllowedSurgeriesToDrugRegimensRecord>>asList(Keys.PK_ALLOWED_SURGERIES_TO_DRUG_REGIMENS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AllowedSurgeriesToDrugRegimensRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AllowedSurgeriesToDrugRegimensRecord, ?>>asList(Keys.ALLOWED_SURGERIES_TO_DRUG_REGIMENS__FK_ALLOWED_SURGERIES_TO_DRUG_REGIMENS_SURGERIES, Keys.ALLOWED_SURGERIES_TO_DRUG_REGIMENS__FK_ALLOWED_SURGERIES_TO_DRUG_REGIMENS_REGIMENS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedSurgeriesToDrugRegimens as(String alias) {
        return new AllowedSurgeriesToDrugRegimens(alias, this);
    }

    /**
     * Rename this table
     */
    public AllowedSurgeriesToDrugRegimens rename(String name) {
        return new AllowedSurgeriesToDrugRegimens(name, null);
    }
}
