/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.CardsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cards extends TableImpl<CardsRecord> {

    private static final long serialVersionUID = 553967388;

    /**
     * The reference instance of <code>wnprc_compliance.cards</code>
     */
    public static final Cards CARDS = new Cards();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardsRecord> getRecordType() {
        return CardsRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.cards.card_id</code>.
     */
    public final TableField<CardsRecord, String> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.cards.exempt</code>.
     */
    public final TableField<CardsRecord, Boolean> EXEMPT = createField("exempt", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.cards.exempt_reason</code>.
     */
    public final TableField<CardsRecord, String> EXEMPT_REASON = createField("exempt_reason", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.cards.container</code>.
     */
    public final TableField<CardsRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.cards.createdby</code>.
     */
    public final TableField<CardsRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.cards.created</code>.
     */
    public final TableField<CardsRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.cards.modifiedby</code>.
     */
    public final TableField<CardsRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.cards.modified</code>.
     */
    public final TableField<CardsRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.cards</code> table reference
     */
    public Cards() {
        this("cards", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.cards</code> table reference
     */
    public Cards(String alias) {
        this(alias, CARDS);
    }

    private Cards(String alias, Table<CardsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cards(String alias, Table<CardsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CardsRecord> getPrimaryKey() {
        return Keys.PK_CARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CardsRecord>> getKeys() {
        return Arrays.<UniqueKey<CardsRecord>>asList(Keys.PK_CARDS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cards as(String alias) {
        return new Cards(alias, this);
    }

    /**
     * Rename this table
     */
    public Cards rename(String name) {
        return new Cards(name, null);
    }
}
