/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.DrugRegimenFrequencyThresholdRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRegimenFrequencyThreshold extends TableImpl<DrugRegimenFrequencyThresholdRecord> {

    private static final long serialVersionUID = -559629402;

    /**
     * The reference instance of <code>wnprc_compliance.drug_regimen_frequency_threshold</code>
     */
    public static final DrugRegimenFrequencyThreshold DRUG_REGIMEN_FREQUENCY_THRESHOLD = new DrugRegimenFrequencyThreshold();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrugRegimenFrequencyThresholdRecord> getRecordType() {
        return DrugRegimenFrequencyThresholdRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.id</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.timeperiod</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, Integer> TIMEPERIOD = createField("timeperiod", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.time_unit</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, String> TIME_UNIT = createField("time_unit", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.type</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.createdby</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.created</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.modifiedby</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.drug_regimen_frequency_threshold.modified</code>.
     */
    public final TableField<DrugRegimenFrequencyThresholdRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.drug_regimen_frequency_threshold</code> table reference
     */
    public DrugRegimenFrequencyThreshold() {
        this("drug_regimen_frequency_threshold", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.drug_regimen_frequency_threshold</code> table reference
     */
    public DrugRegimenFrequencyThreshold(String alias) {
        this(alias, DRUG_REGIMEN_FREQUENCY_THRESHOLD);
    }

    private DrugRegimenFrequencyThreshold(String alias, Table<DrugRegimenFrequencyThresholdRecord> aliased) {
        this(alias, aliased, null);
    }

    private DrugRegimenFrequencyThreshold(String alias, Table<DrugRegimenFrequencyThresholdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DrugRegimenFrequencyThresholdRecord> getPrimaryKey() {
        return Keys.PK_DRUG_REGIMEN_FREQUENCY_THRESHOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DrugRegimenFrequencyThresholdRecord>> getKeys() {
        return Arrays.<UniqueKey<DrugRegimenFrequencyThresholdRecord>>asList(Keys.PK_DRUG_REGIMEN_FREQUENCY_THRESHOLD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRegimenFrequencyThreshold as(String alias) {
        return new DrugRegimenFrequencyThreshold(alias, this);
    }

    /**
     * Rename this table
     */
    public DrugRegimenFrequencyThreshold rename(String name) {
        return new DrugRegimenFrequencyThreshold(name, null);
    }
}
