/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.DrugRoutesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRoutes extends TableImpl<DrugRoutesRecord> {

    private static final long serialVersionUID = -2229778;

    /**
     * The reference instance of <code>wnprc_compliance.drug_routes</code>
     */
    public static final DrugRoutes DRUG_ROUTES = new DrugRoutes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrugRoutesRecord> getRecordType() {
        return DrugRoutesRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.drug_routes.drug_id</code>.
     */
    public final TableField<DrugRoutesRecord, String> DRUG_ID = createField("drug_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.drug_routes.route</code>.
     */
    public final TableField<DrugRoutesRecord, String> ROUTE = createField("route", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.drug_routes.createdby</code>.
     */
    public final TableField<DrugRoutesRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.drug_routes.created</code>.
     */
    public final TableField<DrugRoutesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.drug_routes.modifiedby</code>.
     */
    public final TableField<DrugRoutesRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.drug_routes.modified</code>.
     */
    public final TableField<DrugRoutesRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.drug_routes</code> table reference
     */
    public DrugRoutes() {
        this("drug_routes", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.drug_routes</code> table reference
     */
    public DrugRoutes(String alias) {
        this(alias, DRUG_ROUTES);
    }

    private DrugRoutes(String alias, Table<DrugRoutesRecord> aliased) {
        this(alias, aliased, null);
    }

    private DrugRoutes(String alias, Table<DrugRoutesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DrugRoutesRecord> getPrimaryKey() {
        return Keys.PK_DRUG_ROUTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DrugRoutesRecord>> getKeys() {
        return Arrays.<UniqueKey<DrugRoutesRecord>>asList(Keys.PK_DRUG_ROUTES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DrugRoutesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DrugRoutesRecord, ?>>asList(Keys.DRUG_ROUTES__FK_DRUG_ROUTES_TO_DRUGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRoutes as(String alias) {
        return new DrugRoutes(alias, this);
    }

    /**
     * Rename this table
     */
    public DrugRoutes rename(String name) {
        return new DrugRoutes(name, null);
    }
}
