/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.PendingTbClearancesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PendingTbClearances extends TableImpl<PendingTbClearancesRecord> {

    private static final long serialVersionUID = 1404385216;

    /**
     * The reference instance of <code>wnprc_compliance.pending_tb_clearances</code>
     */
    public static final PendingTbClearances PENDING_TB_CLEARANCES = new PendingTbClearances();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PendingTbClearancesRecord> getRecordType() {
        return PendingTbClearancesRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.id</code>.
     */
    public final TableField<PendingTbClearancesRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.date</code>.
     */
    public final TableField<PendingTbClearancesRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.comment</code>.
     */
    public final TableField<PendingTbClearancesRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.tbclearance_id</code>.
     */
    public final TableField<PendingTbClearancesRecord, String> TBCLEARANCE_ID = createField("tbclearance_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.archived</code>.
     */
    public final TableField<PendingTbClearancesRecord, Boolean> ARCHIVED = createField("archived", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.container</code>.
     */
    public final TableField<PendingTbClearancesRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.createdby</code>.
     */
    public final TableField<PendingTbClearancesRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.created</code>.
     */
    public final TableField<PendingTbClearancesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.modifiedby</code>.
     */
    public final TableField<PendingTbClearancesRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.pending_tb_clearances.modified</code>.
     */
    public final TableField<PendingTbClearancesRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.pending_tb_clearances</code> table reference
     */
    public PendingTbClearances() {
        this("pending_tb_clearances", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.pending_tb_clearances</code> table reference
     */
    public PendingTbClearances(String alias) {
        this(alias, PENDING_TB_CLEARANCES);
    }

    private PendingTbClearances(String alias, Table<PendingTbClearancesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PendingTbClearances(String alias, Table<PendingTbClearancesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PendingTbClearancesRecord> getPrimaryKey() {
        return Keys.PK_PENDING_TB_CLEARANCES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PendingTbClearancesRecord>> getKeys() {
        return Arrays.<UniqueKey<PendingTbClearancesRecord>>asList(Keys.PK_PENDING_TB_CLEARANCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PendingTbClearances as(String alias) {
        return new PendingTbClearances(alias, this);
    }

    /**
     * Rename this table
     */
    public PendingTbClearances rename(String name) {
        return new PendingTbClearances(name, null);
    }
}
