/**
 * This class is generated by jOOQ
 */
package org.labkey.wnprc_compliance.model.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.labkey.wnprc_compliance.model.jooq.Keys;
import org.labkey.wnprc_compliance.model.jooq.WnprcCompliance;
import org.labkey.wnprc_compliance.model.jooq.tables.records.PersonsTbClearancesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonsTbClearances extends TableImpl<PersonsTbClearancesRecord> {

    private static final long serialVersionUID = -1016326877;

    /**
     * The reference instance of <code>wnprc_compliance.persons_tb_clearances</code>
     */
    public static final PersonsTbClearances PERSONS_TB_CLEARANCES = new PersonsTbClearances();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonsTbClearancesRecord> getRecordType() {
        return PersonsTbClearancesRecord.class;
    }

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.person_id</code>.
     */
    public final TableField<PersonsTbClearancesRecord, String> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.clearance_id</code>.
     */
    public final TableField<PersonsTbClearancesRecord, String> CLEARANCE_ID = createField("clearance_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.container</code>.
     */
    public final TableField<PersonsTbClearancesRecord, String> CONTAINER = createField("container", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.createdby</code>.
     */
    public final TableField<PersonsTbClearancesRecord, Integer> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.created</code>.
     */
    public final TableField<PersonsTbClearancesRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.modifiedby</code>.
     */
    public final TableField<PersonsTbClearancesRecord, Integer> MODIFIEDBY = createField("modifiedby", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>wnprc_compliance.persons_tb_clearances.modified</code>.
     */
    public final TableField<PersonsTbClearancesRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>wnprc_compliance.persons_tb_clearances</code> table reference
     */
    public PersonsTbClearances() {
        this("persons_tb_clearances", null);
    }

    /**
     * Create an aliased <code>wnprc_compliance.persons_tb_clearances</code> table reference
     */
    public PersonsTbClearances(String alias) {
        this(alias, PERSONS_TB_CLEARANCES);
    }

    private PersonsTbClearances(String alias, Table<PersonsTbClearancesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersonsTbClearances(String alias, Table<PersonsTbClearancesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return WnprcCompliance.WNPRC_COMPLIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersonsTbClearancesRecord> getPrimaryKey() {
        return Keys.PK_PERSONS_TB_CLEARANCES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersonsTbClearancesRecord>> getKeys() {
        return Arrays.<UniqueKey<PersonsTbClearancesRecord>>asList(Keys.PK_PERSONS_TB_CLEARANCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PersonsTbClearancesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PersonsTbClearancesRecord, ?>>asList(Keys.PERSONS_TB_CLEARANCES__FK_PERSONS_TB_CLEARANCES_PERSONS, Keys.PERSONS_TB_CLEARANCES__FK_PERSONS_TB_CLEARANCES_CLEARANCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonsTbClearances as(String alias) {
        return new PersonsTbClearances(alias, this);
    }

    /**
     * Rename this table
     */
    public PersonsTbClearances rename(String name) {
        return new PersonsTbClearances(name, null);
    }
}
