download.packages('devtools','/tmp/rdownload/', repos='http://cran.us.r-project.org')
download.packages('quadprog','/tmp/rdownload/', repos='http://cran.us.r-project.org')
download.packages('pedigree','/tmp/rdownload/', repos='http://cran.us.r-project.org')
download.packages('Matrix','/tmp/rdownload/',   repos='http://cran.us.r-project.org')
download.packages('RCurl','/tmp/rdownload/',    repos='http://cran.us.r-project.org')
download.packages('kinship2','/tmp/rdownload/',repos='http://cran.us.r-project.org')
download.packages('getopt','/tmp/rdownload/',   repos='http://cran.us.r-project.org')
download.packages('rjson','/tmp/rdownload/',    repos='http://cran.us.r-project.org')
download.packages('dplyr','/tmp/rdownload/',    repos='http://cran.us.r-project.org')
download.packages('remotes','/tmp/rdownload/',  repos='http://cran.us.r-project.org')
download.packages('Rlabkey','/tmp/rdownload/',  repos='http://cran.us.r-project.org')

#require('remotes')
#download_github("luansheng/visPedigree")
