install.packages('devtools', repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('quadprog', repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('pedigree', repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('Matrix',   repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('RCurl',    repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('kinship2', repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('getopt',   repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('rjson',    repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('dplyr',    repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('remotes',  repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')
install.packages('Rlabkey',  repos='http://cran.us.r-project.org', destdir = '/tmp/rdownload/')

require('remotes')
install_github("luansheng/visPedigree")
